### ISSUE TITLE
Check/change the GraphSAGE mapper's behaviour for isolated nodes

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#100]
### Description
Assuming the sampler returns repeated samples of non-existent node id (specified e.g. in StellarGraph.nonexistent_node), this node's feature vector should be an all-zero vector of the same length as those of the existing nodes.

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by adocherty** [comment]
This is superseded by issue #294
