### ISSUE TITLE
CTDNE implementation should avoid overflow when calculating exponential biases

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1010]
### Description

`np.exp` can result in overflow/underflow with very large/small values. 
```
>>> np.exp([100.0, 1000.0, 10000.0, 100000.0])
array([2.68811714e+43,            inf,            inf,            inf])
```
Instead, the exponential biases from the paper are equivalent to using softmax across the available time values so we should just use something like [`scipy.special.softmax`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.softmax.html)

**Comment by huonw** [comment]
Since this just needs an arbitrary scaling value, I think a simpler/more efficient form might be subtracting the largest value off the array, so normalising the largest value in the result to be 1, rather than the sum of the result to be 1; that is, `np.exp(x - x.max())` instead of `np.exp(x)`.

**Comment by kjun9** [comment]
Thanks, I'll use that
