### ISSUE TITLE
GAT input shape error while testing

### ISSUE THREAD

**Issue by ocesp98** [stellargraph/stellargraph#1038]
I used GAT to build a model on the train and validation set. So first, I built the network based on the train and validation set (=9000 rows). The node_features added to the first Stellargraph hence contain also 9000 rows and 5 attributes. 

The problem occurs when I'm predicting on the test set. Given that I want to use the inductive property of GAT, I held the test set separate from the training and validation set. To test, I built a second network where I added the test nodes to the first network (consisting of the train and validation set). This network hence contains 10000 nodes (9000 already existing and 1000 from the test set). The node_features added to this second stellargraph object have a dimension of 10000 rows and 5 attributes. However, when I want to predict on the test generator, I get following error:

> ValueError: Error when checking input: expected input_1 to have shape (9000, 5) but got array with shape (10000, 5)

I used following code:

`stelgr = sg.StellarGraph(H, node_features=node_features) #this is for training`
`generator = FullBatchNodeGenerator(stelgr, method="gat")`
`train_gen = generator.flow(train_data.index, train_targets)`
`gat = GAT(layer_sizes=[32, 32, 1],
    activations=["relu", "relu", "sigmoid"],
    attn_heads=8,
    generator=generator,
    in_dropout=0.4,
    attn_dropout=0.3)`

Then I trained the model. To test, I rebuilt the network:

`stelt = sg.StellarGraph(Ht, node_features = node_features2)`
`generator = FullBatchNodeGenerator(stelt, method="gat")`
`test_gen = generator.flow(test_data.index, test_targets)`

So Ht is the full network with the test nodes added. Node_features2 contains all features, including the features for the test set and has shape (10000,5). Node_features only contains the features for the train and validation set and has shape (9000,5).

The full error is as follows:

>  ValueError                                Traceback (most recent call last)
> <ipython-input-84-c4c1e4285085> in <module>
>       1 #t_nodes = test_data.index
>       2 #t_mapper = generator.flow(t_nodes)
> ----> 3 t_predictions = model.predict_generator(test_gen)
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training.py in predict_generator(self, generator, steps, callbacks, max_queue_size, workers, use_multiprocessing, verbose)
>    1553         use_multiprocessing=use_multiprocessing,
>    1554         verbose=verbose,
> -> 1555         callbacks=callbacks)
>    1556 
>    1557   def _validate_compile_param_for_distribution_strategy(
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
>     262 
>     263       is_deferred = not model._is_compiled
> --> 264       batch_outs = batch_function(*batch_data)
>     265       if not isinstance(batch_outs, list):
>     266         batch_outs = [batch_outs]
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training_generator.py in predict_on_batch(x, y, sample_weights)
>     534     # 1, 2, or 3-tuples from generator
>     535     def predict_on_batch(x, y=None, sample_weights=None):  # pylint: disable=unused-argument
> --> 536       return model.predict_on_batch(x)
>     537 
>     538     f = predict_on_batch
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training.py in predict_on_batch(self, x)
>    1279     # Validate and standardize user data.
>    1280     inputs, _, _ = self._standardize_user_data(
> -> 1281         x, extract_tensors_from_dataset=True)
>    1282     # If `self._distribution_strategy` is True, then we are in a replica context
>    1283     # at this point.
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
>    2649           feed_input_shapes,
>    2650           check_batch_axis=False,  # Don't enforce the batch size.
> -> 2651           exception_prefix='input')
>    2652 
>    2653     if y is not None:
> 
> ~\Anaconda3\envs\StellarGraph2\lib\site-packages\tensorflow\python\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
>     383                              ': expected ' + names[i] + ' to have shape ' +
>     384                              str(shape) + ' but got array with shape ' +
> --> 385                              str(data_shape))
>     386   return data
>     387 
> 
> ValueError: Error when checking input: expected input_1 to have shape (9000, 5) but got array with shape (10000, 5)

I use Python 3.6, StellarGraph 0.8.4 and NetworkX 2.3

The goal of my code is to use the GAT model to predict on a separate test set (that was not available in the network used to train on) in order to leverage its inductive property. 

Is there anything I do wrong?

Thank you in advance!

**Comment by kjun9** [comment]
Hi @ocesp98 

Thanks for using StellarGraph and filing this detailed issue! 

Unfortunately, the current implementation of GAT in StellarGraph doesn't support inductive learning. The shapes of the tensors are defined when building the model, so if the test graph contains a different number of nodes than your training graph, it will result in the sort of error you've encountered where there's a dimension mismatch.

We'll update this issue once we have a fix!

For now, if you're looking for inductive algorithms for node classification in general, you could try `GraphSAGE` instead - you can find the demo for inductive representation learning [here](https://github.com/stellargraph/stellargraph/blob/develop/demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb) which could be updated to do node classification.

**Comment by PantelisElinas** [comment]
Hi @ocesp98 and @kjun9 

I'd just like to add that our GraphSAGE implementation supports an attentional aggregator so that you can use it to build a sampled GAT model and then, of course as @kjun9 suggested, use it for inductive representation learning.

See https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.layer.graphsage.AttentionalAggregator

Regards,

P.

**Comment by ocesp98** [comment]
Thank you for your answers!

So, if I take a test data set of 9000 rows, then this problem will be solved and GAT will be semi-inductive (meaning then that it is inductive if the test set size equals the train set size)? 

For the AttentionalAggregator, is it the same code as when you use the meanAggregator or de we then also have to use the FullBatchNodeGenerator?

Kind regards

**Comment by PantelisElinas** [comment]
Hi @ocesp98 

you are correct about setting the sizes of the train and test sets to equal. This will allow you to make predictions for a new graph with a GAT model.

To use the `AttentionalAggregator` with GraphSAGE, you just need to specify it when creating the GraphSAGE model. See the documentation linked below and pay attention to the parameter `aggregator` that defaults to using the `MeanAggregator`. You do not need to use the FullBatNodeGenerator; other than the one small change, everything else in your code should remain the same. https://stellargraph.readthedocs.io/en/stable/api.html#module-stellargraph.layer.graphsage

Regards,

P.

**Comment by ocesp98** [comment]
Ok thank you very much. I will try both solutions.
