### ISSUE TITLE
Provide links to some online compute service for running notebooks

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1091]
### Description

Our notebooks and StellarGraph more generally will be easiest to get started with if people can click a button and have a working environment, immediately. There's a few services that this may work with:

- https://colab.research.google.com
- https://mybinder.org

**Comment by huonw** [comment]
Binder seems to be used by big libraries like scikit-learn (e.g. [they have a "Launch: binder" button on many notebooks](https://scikit-learn.org/stable/auto_examples/semi_supervised/plot_label_propagation_digits_active_learning.html#sphx-glr-auto-examples-semi-supervised-plot-label-propagation-digits-active-learning-py)), it can build an image from a repo so that all the dependencies are available without needing custom code in each notebook.

Relevant doc links:

- https://mybinder.readthedocs.io/en/latest/sample_repos.html#python-package-with-setup-py
- https://mybinder.readthedocs.io/en/latest/faq.html#how-much-memory-am-i-given-when-using-binder

**Comment by timpitman** [comment]
I think many of our notebooks won't work on Bindr - it's 1 to 2GB RAM: https://mybinder.readthedocs.io/en/latest/faq.html#user-memory

**Comment by huonw** [comment]
That's true. Maybe we could only put links on the ones that do work? I feel like the Binder start-up experience will be better, since it can have all the right packages installed out of the box.

(Arguably, it's weird that we need more than 2GB for working with the (relatively) small graphs that our demo notebooks use, but fixing that is, of course, hard...)

**Comment by timpitman** [comment]
I agree that bindr is nice since it doesn't need package installs or any account.  How about:
1. bindr for some of the notebooks that don't need much memory (eg I tried graphSAGE directed NAI and it worked)
2. Colab links (and pip cell) on all notebooks

**Comment by huonw** [comment]
That sounds reasonable.

> Colab links (and pip cell) on all notebooks

Just to be clear, you mean even the notebooks with binder links? It's a bit unfortunate that this means we don't quite get to fully benefit from the convenience of binder not requiring extra code. Are you thinking that it's good to do this because Colab seems to have more powerful compute and thus will help even on notebooks that don't use much memory?

**Comment by timpitman** [comment]
My thought here was that Colab is less limited (resources, runtime, timeouts etc) and has its own community as a popular notebook platform - it would be great if all notebooks would work even though I admit the extra cell looks ugly.  I wouldn't be surprised if people start with our basic notebooks, then modify for their own use.

Bindr (when used) would ignore the cell; performance wouldn't be impacted.

**Comment by huonw** [comment]
Yeah, the ugliness is my main concern, but I think the pain of going through and editing all 40 notebooks is non-trivial (although, I suppose we have to do that to add the links anyway, so pasting in an extra cell shouldn't be too bad).
