### ISSUE TITLE
Update Conda `meta.yaml` and document how it should be maintained

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1166]
### Describe the bug

`conda build` failed during release 0.11.0 from having outdated information in `meta.yaml`:
```
Traceback (most recent call last):
  File "/Users/jun021/miniconda3/envs/stellargraph-dev/conda-bld/stellargraph_1585130950934/test_tmp/run_test.py", line 20, in <module>
import: 'stellargraph'
    import stellargraph.utils.saliency_maps
import: 'stellargraph.core'
ModuleNotFoundError: No module named 'stellargraph.utils.saliency_maps'
import: 'stellargraph.data'
import: 'stellargraph.layer'
import: 'stellargraph.mapper'
import: 'stellargraph.utils'
import: 'stellargraph.utils.saliency_maps'
Tests failed for stellargraph-0.11.0-py_0.tar.bz2 - moving package to /Users/jun021/miniconda3/envs/stellargraph-dev/conda-bld/broken
WARNING:conda_build.build:Tests failed for stellargraph-0.11.0-py_0.tar.bz2 - moving package to /Users/jun021/miniconda3/envs/stellargraph-dev/conda-bld/broken
WARNING conda_build.build:tests_failed(2231): Tests failed for stellargraph-0.11.0-py_0.tar.bz2 - moving package to /Users/jun021/miniconda3/envs/stellargraph-dev/conda-bld/broken
TESTS FAILED: stellargraph-0.11.0-py_0.tar.bz2
```

The requirements defined in `meta.yaml` were also not updated for a few releases so despite building successfully, those releases uploaded in conda cloud are broken. We should update `meta.yaml` to be more optimised and easier to maintain, and document when to make updates (e.g. during release).

**Comment by timpitman** [comment]
See https://github.com/stellargraph/stellargraph/pull/1165

**Comment by timpitman** [comment]
#1165 improves the Conda package, and integrates it into CI so that it's continually tested and we'll know as soon as it breaks - that way it will be updated immediately inside PR's, rather than waiting for the release.
