### ISSUE TITLE
Check stellargraph version in demo notebooks

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1172]
# Resolving the error or warning from a notebook

## StellarGraph library version is *older* than the notebook

The error from the notebook will be similar to:
```
This notebook requires StellarGraph version 1.0.0, but an older version 1.0.0rc1 is installed.
```

### Resolution

You will need to either:

1. update the installed version of StellarGraph (**recommended**):
  ```
  pip install --upgrade stellargraph
  ```
2. use a version of the notebook that matches the installed version of StellarGraph (see `stellargraph.__version__` in Python, or `pip freeze | grep stellargraph` on the command line).

  An appropriate version can be found online at https://github.com/stellargraph/stellargraph/tree/v$YOUR_VERSION_HERE/demos (replace `$YOUR_VERSION_HERE` with the version number, like `1.0.0`), or in a git checkout with `git checkout v$YOUR_VERSION_HERE` (like `git checkout v1.0.0`).

## StellarGraph library version is *newer* than the notebook

The warning from the notebook will be similar to:
```
This notebook is designed for an older StellarGraph version 0.11.0 and may not function correctly with the newer installed version 1.0.0.
```

### Resolution

Make sure the version of the notebook matches the version of Stellargraph (see point 2 in the previous section).

If you're simply working through the notebook as a demonstration, it's best to use the most recent version of StellarGraph, by downloading the most recent release version of the notebook from the GitHub master branch https://github.com/stellargraph/stellargraph/tree/master/demos . At the same time, it's worth checking that you also have the latest StellarGraph installed:
```
pip install --upgrade stellargraph
```

<details><summary>Old Description</summary>

(This is the description of the issue before we addressed in #1242)

Demo Jupyter notebooks for StellarGraph are designed and tested with specific versions of StellarGraph.  As the StellarGraph API evolves, notebooks are updated and tested on CI to confirm that they work correctly with the latest version of StellarGraph.

This presents a problem for our users who may download notebooks (from 'develop' branch or 'release'), and then be running them with an older version of StellarGraph.

Notebooks can now check that they are running with the correct version of StellarGraph, and report an error if the version of the StellarGraph library is older, or a warning if the version of StellarGraph library is newer.

</details>

**Comment by pritamarnab** [comment]
In google colab I am using the following code

# install StellarGraph if running on Google Colab
import sys
if 'google.colab' in sys.modules:
  %pip install -q stellargraph[demos]==1.2.1

Even two weeks back it worked, but it is showing the following error

ERROR: Could not find a version that satisfies the requirement stellargraph[demos]==1.2.1 (from versions: none)
ERROR: No matching distribution found for stellargraph[demos]==1.2.1

**Comment by amanredmi** [comment]
same problem I am also facing

**Comment by sergiomorapardo** [comment]
Same problem here! Does anyone know if this package still has maintenance?

**Comment by Dixit-529** [comment]
@huonw 
i can download the package stellaergraph and demos but i can't import those packages.
i have also run pip show stellargraph and in the output of this cammand it also show stellargraph package is there.but can't import.
someone can help me with this issue?? thanks in advance
pyhton version 3.7.11

<img width="785" alt="Screenshot 2024-02-17 230916" src="https://github.com/stellargraph/stellargraph/assets/98507705/f464cd38-7be2-4509-afeb-aff247e08e17">
