### ISSUE TITLE
Improve documentation for how to download and run demos

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1202]
### Description

Raised in #1171, our documentation does not clearly explain that demos are not installed via Conda or Pip and must be downloaded separately:

>> You can start working with the examples immediately in Google Colab or Binder by clicking the  and  badges within each Jupyter notebook. You can also run them locally, after installing StellarGraph. One of the following might be appropriate:

We need clear instructions on downloading the demos (as opposed to just installing demo dependencies).

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
This came up in dogfooding too (https://github.com/stellargraph/stellargraph/issues/1333)

**Comment by kjun9** [comment]
Note that this isn't quite fully resolved by #1377 (https://github.com/stellargraph/stellargraph/pull/1377#pullrequestreview-400801873)

We should definitely add the instructions in `demos/README` too, and think a bit about how to make it easier to download a demo while viewing a specific demo in github - discussion in this issue might be relevant https://github.com/stellargraph/stellargraph/issues/1390
