### ISSUE TITLE
Cleanup NodeSplitter class

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#122]
### Description

The NodeSplitter class was "inherited" from Stellar 0.1 and it comes with lots of functionality that is not needed for the machine learning library or it has already been implemented in different modules, e.g., load_data method. 

We want to simplify NodeSplitter with only the necessary functionality for the Stellar ML library. 

### User Story
As a: Research Engineer
I want: the components of the Stellar ML library to include the needed functionality with no redundancy
so that: the Stellar ML library is easy to maintain, extend, and use.

### Done Checklist (Development)
- [ ] Remove no longer needed functionality in NodeSplitter class
- [ ] Update unit test accordingly
- [ ] Pull request

**Comment by huonw** [comment]
With https://github.com/stellargraph/stellargraph/pull/887, this class no longer exists, so this issue is done.
