### ISSUE TITLE
Run tests with TF GPU support to catch any GPU vs. CPU behaviour differences

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1227]
### Description

Tensorflow can run on both CPU and GPU (and TPU), and some functions have behaviour differences, for instance

-  [`tf.nn.embedding_lookup`](https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup) (at least, according to the docs of [`tf.compat.v1.nn.embedding_lookup`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/embedding_lookup)):

   > validate_indices: DEPRECATED. If this operation is assigned to CPU, values in indices are always validated to be within range. If assigned to GPU, out-of-bound indices result in safe but unspecified behavior, which may include raising an error.

   This parameter doesn't exist in `tf.nn.embedding_lookup` and defaults to False in `tf.compat.v1.nn.embedding_lookup`

- [`tf.gather`](https://www.tensorflow.org/api_docs/python/tf/gather)

  > Note that on CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value.

One option would be to have an agent queue that includes GPU (e.g. using [g4dn.xlarge](https://www.ec2instances.info/?selected=g4dn.xlarge) which seems to be the cheapest GPU-supporting EC2 instance at USD$0.526/hour on demand) and run tests using it only occasionally (e.g. once per day, or on Tuesdays and Thursdays each week). The latency of these tests wouldn't be important, and so could have a small limit, like 1, to avoid costs spiralling out of control even if we make a mistake and leave it running for an extended period.

Another would be having buildkite run on a machine-with-GPU that we own.

**Comment by TheDen** [comment]
The `buildkite-g4dnxlarge` agent pool has been created.

- Tag is `queue=g4dnxlarge`
- EC2 instance is `g4dn.xlarge`
- Min scale is `0`, max is `1`
- Scale down period is `600s` (same as the t2large pool)
- EBS volume is 80GBs (same as the t2large pool)
