### ISSUE TITLE
Node classification over multiple disconnected graphs 

### ISSUE THREAD

**Issue by qillbel** [stellargraph/stellargraph#1234]
### Description

Dear all,

Imagine I have many small graphs (approximately 1000 nodes for each graph) and I have all nodes labelled or annotated in all graphs. In this case, I assigned 1 (out of 7 labelled) to each node. Along with the labels, I do have 5 features (2 binary features with Yes or No, and 3 multiclass features with range between 0-20).

For the edge, I have undirected edges in each graph with 2 features weight (float) and feel (binary integer).

My aim is to predict the unlabelled/unannotated nodes in a completely new graph. A simple implementation would help me a lot.

### User Story

**As** a researcher

**I want to do node classification.
**So that I can predict the unlabelled/unannotated nodes in a completely new graph

**Comment by huonw** [comment]
Hi @qillbel, thanks for trying StellarGraph and providing such clear information about your task.

It sounds like you're trying to do "inductive" node classification, generalising to unseen nodes and edges (in your case, the whole graphs). This can be done most directly with 

- GraphSAGE: [demo of inductive prediction](https://github.com/stellargraph/stellargraph/blob/master/demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb), the inductive part starts at "Making predictions with the model"
- HinSAGE: a generalisation of GraphSAGE to work on graphs with more than one node or edge type (I don't think this applies to your graph, so GraphSAGE is simpler to work with)
- Cluster-GCN: [demo of usage](https://github.com/stellargraph/stellargraph/blob/master/demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb), inductive prediction involves creating a new `StellarGraph` and `ClusterNodeGenerator` for the completely new graph, similar to how the GraphSAGE example creates a new `GraphSAGENodeGenerator` with the `graph_full` object)

For training, I would suggest combining the small graphs into one large `StellarGraph` (which will have several disconnected subgraphs, which is fine).

Does this help get you started?

(Also, just FYI, it's an long public holiday for Easter here in Australia so we may be a bit slow to reply for the next few days, but we're enthusiastic to help!)

**Comment by huonw** [comment]
It's been a month without any update, so I'm going to assume that the problem is resolved. If we haven't heard otherwise in a week or so, we'll close. (But, even if we close, feel free to just let us know later, and we can reopen/continue the discussion.)
