### ISSUE TITLE
Return multiple arrays instead of zipping arrays into a list in `StellarGraph`

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#1238]
Some `StellarGraph` methods zip multiple numpy arrays and return them as one list, these could optimized to return seperate array.

These method are:

- `edges`
- `_transform_edges`
- `_adjacency_types` (maybe?)
- `_unique_type_triples` (maybe?)

**Comment by huonw** [comment]
Relates to #718.
