### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1241]
### Description

Once we support tensorflow 2.2, we remove the blocker to python 3.8 support - it should be possible to test on CI and remove our version restriction.

See tensorflow announcement here: https://github.com/tensorflow/tensorflow/issues/33374

And our previous experiment here:  https://github.com/stellargraph/stellargraph/pull/673

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by kjun9** [comment]
Hmm just found something in the release notes for the latest RC https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc3
> Due to certain unforeseen circumstances, we are unable to release MacOS py3.8 binaries, but Windows/Linux binaries for py3.8 are available.

**Comment by timpitman** [comment]
I'm not sure that's true though: the packages are up on PyPI: https://pypi.org/project/tensorflow/2.2.0rc3/#files

**Comment by yvonnegh** [comment]
Huon will do a test against rc4.
