### ISSUE TITLE
Make it easier to start up neo4j to run notebooks

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1250]
### Description

Currently we can build the neo4j docker image being used in CI like so:
```
docker-compose -f docker-compose.yml -f .buildkite/docker-compose.yml build --build-arg NEO4J_VERSION=4.0 neo4j
```
and run it via:
```
docker run -it -e NEO4J_AUTH=none -p 7687:7687 -p 7474:7474 stellargraph_neo4j:latest
```
We should make these instructions/script available somewhere for development, or possibly available in general.

### User Story

**As** a developer

**I want to** run neo4j notebooks

**So that** verify them after I make changes

**Comment by huonw** [comment]
cc @kieranricardo
