### ISSUE TITLE
Add a glossary to have a central place for definitions/links

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1268]
### Description

In #1200/#1087, it was noted that there's a variety of technical terms that we sort of have to define  ad-hoc:

- graph things like "node", "vertex", "edge", "link", ...
- graph ML things like "node classification", "link prediction"
- even ML terminology like "inductive"

If we had a central glossary, we can write these done once and link to them.

**Comment by yvonnegh** [comment]
Potentially a lot of work, save for 1.1
