### ISSUE TITLE
Demos in readthedocs have broken links

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1292]
### Describe the bug

Follow-up from #1279

Notebooks were added to our readthedocs documentation by using `nbsphinx`, but seems like quite a number of links got broken. For example in `loading-saving-neo4j`:
![image.png](https://images.zenhubusercontent.com/5ad3f71c4b5806bc2bcf28ff/61807d53-1420-4d96-ae40-8afa1aee045e)

**Comment by huonw** [comment]
I think there's two causes here:

- some of the links have nested markup, in particular code https://github.com/spatialaudio/nbsphinx/issues/301, e.g. https://stellargraph.readthedocs.io/en/v1.0.0rc1/demos/basics/loading-networkx.html#Loading-from-many-graph-formats,-via-NetworkX
  > A NetworkX graph can be created in many ways, including manually via `` `add_...`` methods <https://networkx.github.io/documentation/stable/tutorial.html#creating-a-graph>\`__, and by [reading from files in many formats](https://networkx.github.io/documentation/stable/reference/readwrite/index.html). In this tutorial, we’ll only use the first one.
- some files don't exist in the sphinx docs (yet), like the `../README.md` in the screenshot in the issue (#1298)

**Comment by huonw** [comment]
Now that #1394 and #1401 have landed, I think most of these are fixed. Scrolling through some random notebooks, they all seem to look good.
