### ISSUE TITLE
Unit tests for DGCNN

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1297]
### Description

#1212 implements DGCNN as `@experimental`. It doesn't have any unit tests, but should before becoming non-`@experimental`.

**Comment by huonw** [comment]
This may not be necessary with #1373.

**Comment by huonw** [comment]
I've added a simple test to #1373, which I think is enough.

**Comment by PantelisElinas** [comment]
I think it looks sufficient. There is little more to check in the re-factored version.
