### ISSUE TITLE
Add stratified sampling for NodeSplitter

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#130]
### User Story
As a:
I want:
so that:

### Done Checklist (Development)
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [ ] Team demo
- [ ] Mini-meetup talk
- [ ] Stakeholder sign-off

### Done Checklist (Research)
- [ ] Code Review
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [ ] Team talk
- [ ] Mini-meetup talk

### Done Checklist (Bug)
- [ ] Bug fixed
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by huonw** [comment]
`NodeSplitter` no longer exists (#885/#887), so moving this to Done.
