### ISSUE TITLE
METR-LA dataset download

### ISSUE THREAD

**Issue by habiba-h** [stellargraph/stellargraph#1303]
Currently, the METR-LA dataset has to be manually downloaded from:  [(https://github.com/lehaifeng/T-GCN/tree/master/data)] for the `gcn_lstm-LA.ipynb` demo notebook. 
This needs to be resolved in future

**Comment by timpitman** [comment]
See https://github.com/stellargraph/stellargraph/pull/1325 for the download fix, however documentation and tests of the other code in the datasets class is still needed
