### ISSUE TITLE
`StellarGraph._edges._edges_in_dict` and`StellarGraph._edges._edges_out_dict` are unused for undirected graphs

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#1316]
`StellarGraph._edges._edges_in_dict` and`StellarGraph._edge._edges_out_dict` consume a large amount of memory - %40 of all the memory allocated to `StellarGraph._edges` but aren't used for undirected graphs.

**Comment by huonw** [comment]
This could be done in a similar manner to #1291 #1295, where these are just computed lazily, only when required.
