### ISSUE TITLE
Loading code in demos should link back to "here's how to load"

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1330]
### Describe the bug

The dataset module makes our demos cleaner, but it does make it harder for a user to work out how to load their own data. We should link to the demos for loading data to clarify this.

(StellarGraph 1.0.0rc1 dogfooding)

**Comment by yvonnegh** [comment]
Hidden loading code in datasets class, need to point back to it.
Could be automated.
More notebook operations...

Is important - was consistent in dogfooding that users didn't know how to load data and had to work it out.

Could do manually in each notebook but preference is to do automatically.
Maybe when dataset load is called, that can print output back to notebook formatted with link to other notebooks to explain how to load data, and readTheDocs for loading function.
or
Tag loading cell and markdown cell before it with a link or description to appropriate destination.
