### ISSUE TITLE
Supervised graph classification notebook training runs for a long time without progress

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1335]
### Describe the bug

The supervised graph classification notebook defaults to training 50 models (10 folds with 5 restarts per folds) for up to 500 epochs. It does this with `verbose=0` in the Keras `Model` method calls, and no other progress information (other than `[...]`'s from #826), so it's not obvious to the user that it's making progress.

(StellarGraph 1.0.0rc1 dogfooding)

**Comment by kieranricardo** [comment]
Possible can use `tqdm` module

**Comment by PantelisElinas** [comment]
I understand that it might run for a while although it uses early stopping and hardly ever trains for 500 epochs, but how is this a bug? Are you suggesting that we need to add a cautionary note about training time somewhere in the notebook?

**Comment by huonw** [comment]
The training cell trains silently for many minutes. On my machine, it's about 10-15s/restart, and thus 60s per fold, meaning 10 minutes just to run the training cell without any feedback.

This is suboptimal for a few reasons:

- the notebook just takes a long time to run, making it harder for us to edit and much more annoying for a user to work with.
- silent work always leaves someone with a "is it really doing anything" question in their head. I know I'm always concerned when running documentation or examples (i.e. code that I didn't write and/or am otherwise unfamiliar with) that take a long time because I don't know if it's hanging because I've misconfigured my installation somehow (or something like that). This is what the "it's not obvious to the user that it's making progress" in the original issue description is referring to.

Between these, I think it's likely that a non-trivial portion of potential users will give up ("I let it run for 5 minutes and nothing happened") or come away with a poor impression. The StellarGraph dogfooder who I observed using this notebook got a little frustrated in practice, too.

One simple way to address at least the second point is @kieranricardo's comment: the [`tqdm`](https://github.com/tqdm/tqdm) library could be used to wrap the training loops like `tqdm.tqdm(model_selection.StratifiedKFold(...))` and `tqdm.tqdm(range(num_restarts))` (it even automatically supports nice rendering for [nested loops](https://github.com/tqdm/tqdm#nested-progress-bars)) and so give some feedback to the user. This will ensure they (a) understand that it's working, and (b) give them an estimate for how long it will take.

Something more invasive would be to make it run faster, because this is meant to serve as documentation and an example starting point for users, and _not_ a real machine learning pipeline. I think running faster will make it better and more "vibrant" documentation, because a user will feel less obstacle to tweaking things and re-training. A simple way to do this would be to go down to something like `folds = 4` and `num_restarts = 2`, with or without a comment that they can/should be increased as appropriate for the user's tasks. Those particular parameters seem to reduce the time for the training cell to ~2 minutes on my machine, which is still quite long, but much more reasonable.

(Note that this gets worse with TensorFlow 2.2 that's likely to be released soon: at least with TF 2.1 we have "progress updates" in the form of each `fit` call emitting `WARNING:tensorflow:sample_weight modes were coerced from ... to ['...']`. This TF bug is fixed in 2.2, and that output disappears, so the cell will be completely silent for ~10 minutes.)

**Comment by PantelisElinas** [comment]
I had a look at adding `tqdm` and it does not produce a particularly pleasing output or give an indication of progress in this case. Generally, looks to me that we can just set `verbose=1` or `verbose=2` in the call to `fit` and then the user will receive feedback of progress and at least will know that something is happening. Anyway, I'm sure you will figure out a better way to do it.

**Comment by yvonnegh** [comment]
Needs further discussion around style of feedback and to balance with amount of output (not 1000s of lines when training 50 models).
