### ISSUE TITLE
PaddedGraphGenerator.flow could detect common error of list of StellarGraph

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1337]
### Describe the bug

PaddedGraphGenerator.flow expects a list/sequence of integers (of indices into the list of graphs passed to PaddedGraphGenerator). Users are likely to make a mistake and pass in a list of graphs themselves, because it's easy to do:

```python
train_graphs, test_graphs = model_selection.train_test_split(graphs, ...)
train_gen = generator.flow(train_graphs)
```

The correct thing is to do:

```python
train_graphs, test_graphs = model_selection.train_test_split(range(len(graphs)), ...)
train_gen = generator.flow(train_graphs)
```

When we detect a type error, we could check if it's a `StellarGraph` and give a more specific error.

(StellarGraph 1.0.0rc1 dogfooding)

**Comment by kieranricardo** [comment]
Potentiall we could resolve this by making the generator accept a list of `StellarGraph`s

**Comment by yvonnegh** [comment]
Options: Make a better error or not an error
Probably leaning towards not an error.
