### ISSUE TITLE
Empty graph fails in PaddedGraphGenerator

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1338]
### Describe the bug

Passing in an empty graph (no nodes or edges) into the PaddedGraphGenerator results in an error like "k exceeds matrix dimension".

(StellarGraph 1.0.0rc1 dogfooding)

**Comment by kieranricardo** [comment]
Currently no reproducable example

**Comment by huonw** [comment]
The root cause of this is `sparse.diagonal()` fails if `sparse.shape == (0, 0)` (where `sparse` is a `scipy` sparse matrix https://docs.scipy.org/doc/scipy/reference/sparse.html). `StellarGraph.to_adjacency_matrix` hits this for an undirected graph, if the graph is empty or the `nodes` filtering list is empty.
