### ISSUE TITLE
Loading data demos encourage skipping but don't repeat relevant info

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1340]
### Describe the bug

The 'basics/loading-*' demos explicitly encourage readers to jump to the section most relevant to them, but there's some piece of information that are only written in one place, such as the `node_type_default=...` argument and links to relevant documentation.

(StellarGraph 1.0.0rc1 dogfooding.)

**Comment by kieranricardo** [comment]
potentially, stop explicitly encouraging people to skip.
