### ISSUE TITLE
Automatically infer node type arguments for graphs with only one node type

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#1343]
When creating a `StellarGraph` with only one node type the user can pass in the nodes without specifying a node type and `StellarGraph` automically sets a default node type. What this default node type is  or how to get it is not immediately apparent.

Using HinSAGE requires specifying a node type but in the case of heterogenous graph one node type this may not obvioius. This issue is allow HinSAGE to automatically infer the head node type as the defulat node type in cases where there is only one node type.

(StellarGraph 1.0.0rc1 dogfooding.)

**Comment by huonw** [comment]
I think this is more general than HinSAGE, e.g. it applies to `node_features(node_type=...)`. In a homogeneous graph, `graph.node_features()` should work.

Also, this would resolve #1023.
