### ISSUE TITLE
DeepGraphConvolutionalNeuralNetwork output is non-obvious to get down to one element per output

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1344]
### Describe the bug

The DeepGraphConvolutionalNeuralNetwork model has rank-3 output, like `(batch_size, <something>, <other thing>)`, and then there's the various convolutional processing from the paper, followed by an output layer. 

Copying the suggested processing from the documentation:

```python
generator = PaddedGraphGenerator(graphs)
model = DeepGraphConvolutionalNeuralNetwork(
                 layer_sizes=[32, 32, 32, 1],
                 activations=["tanh","tanh", "tanh", "tanh"],
                 generator=generator,
    )
x_inp, x_out = model.in_out_tensors()

x_out = Conv1D(filters=16, kernel_size=97, strides=97)(x_out)
x_out = MaxPool1D(pool_size=2)(x_out)
x_out = Conv1D(filters=32, kernel_size=5, strides=1)(x_out)
x_out = Dense(units=128, activation="relu")(x_out)
x_out = Dropout(rate=0.5)(x_out)
predictions = Dense(units=1, activation="sigmoid")(x_out)
```

Should be resulting in a tensor of shape `(batch_size, 1)`, i.e. one prediction per input graph in the batch, but it actually results in a tensor of shape `(batch_size, x, 1)` where `x > 1`, meaning multiple predictions per batch element. This seems unexpected.

One way to work around this is to flatten to a rank-2 tensor, via `x_out = Reshape((...,))(x_out)` somewhere before the last `Dense`. However, it's not obvious to me what `...` should be (in the general case).

(StellarGraph 1.0.0rc1 dogfooding.)

**Comment by PantelisElinas** [comment]
This is fixed in #1319
