### ISSUE TITLE
Package relevant GCN-LSTM data preparation methods into StellarGraph

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#1345]
Currently GCN-LSTM accepts a adjacency matrix and sliced timeseries directly. This issue is to provide `stellargraph` functionality to prepare the data in this format.

One option is to create a `StellarGraph` object with the time series as node features and create a stellargaph  `Generator` to yield the adjacency matrix and sliced time series from a `StellarGraph` object.

(StellarGraph 1.0.0rc1 dogfooding.)

**Comment by huonw** [comment]
We should consider looking at how other libraries (e.g. non-graph time series ones) handle this sort of data-splitting-for-evaluation problem, if they do. @annitrolla mentioned https://github.com/facebook/prophet as a potential example.

**Comment by kieranricardo** [comment]
Potentially pull some pre-rpocessing code into the demo notebook.
