### ISSUE TITLE
Spellcheck notebooks

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1368]
### Description

Many of our notebooks have typos in them. It'd be good to at least do a manual pass to check them before 1.0, and even check them automatically.

**Comment by huonw** [comment]
@timpitman had the idea that we could potentially use the nbsphinx/HTML conversion to do the checking here. If that doesn't work, another way would be to convert them to markdown with nbconvert and then use a markdown spell checker.

**Comment by yvonnegh** [comment]
May create too much fixing work for 1.0
User noticed typos and submitted PR.
Filed a follow up issue about other potential PRs.

Good opportunity to get people contributing!
