### ISSUE TITLE
DeepGraphConvolutionalNeuralNetwork class name doesn't match convention

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1370]
### Description

The  `DeepGraphConvolutionalNeuralNetwork` class name doesn't match the abbreviation convention we use for the rest of the library, such as `GCN` instead of `GraphConvolutionalNetwork`.

https://github.com/stellargraph/stellargraph/blob/ff62cc6355a7a17358dc29766ec3d3e935734745/stellargraph/layer/graph_classification.py#L186

It should probably be `DGCNN`, which both matches StellarGraph's convention and [the paper](https://www.cse.wustl.edu/~muhan/papers/AAAI_2018_DGCNN.pdf) (e.g. Section 2's title and Table 2).

**Comment by PantelisElinas** [comment]
I suggest that renaming to DGCNN will be confusing as there is also the following method with the same acronym Dynamic Graph CNN,

see https://github.com/WangYueFt/dgcnn

**Comment by huonw** [comment]
That's true. The "ConvolutionalNeuralNetwork" section of the name is rather long (especially the NeuralNetwork bit), as is `Graph`. Maybe `DeepGCNN` for our current one, and then the other can be `DynamicGCNN` if it gets implemented. #1421
