### ISSUE TITLE
Docker image 'latest' tag is develop, not master

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1382]
### Describe the bug

The `stellargraph/stellargraph` docker image (https://hub.docker.com/repository/docker/stellargraph/stellargraph) is published from the `develop` branch to `latest`, meaning there's no releases for our stable `master` releases, and `docker run stellargraph/stellargraph:latest` uses the `develop` branch, not one of our releases. 

If we're publishing docker images, we should make sure we emphasise the stable ones more.

This is coordinated by:

https://github.com/stellargraph/stellargraph/blob/492c4e30d962a9e4ce73d37924ef6e4b1bb597ea/.buildkite/hooks/pre-command#L4-L16

https://github.com/stellargraph/stellargraph/blob/492c4e30d962a9e4ce73d37924ef6e4b1bb597ea/.buildkite/pipeline.yml#L241-L248

### Environment

StellarGraph 492c4e30d962a9e4ce73d37924ef6e4b1bb597ea

### Additional context

N/A

**Comment by timpitman** [comment]
Does anyone even use our docker images?

**Comment by huonw** [comment]
I think our CI will do at most two pulls per build: 

- one for the cache when building
- one for the push step, to get the image and repush it

https://github.com/stellargraph/stellargraph/blob/1cca6b6c6f4cd1fea7c6932918cba18d15eef6d4/.buildkite/pipeline.yml#L232-L260

| pipeline | builds |
|---|---|
| `stellargraph-public` | 3545 |
| `stellargraph` (now unused) | 1866 |
| **Total** | **5411** |

This implies that at most 10822 of the pulls are from our CI. I don't _think_ any of our other pipelines use this docker image. I don't know if 15k pulls is a lot.

Removing the image would certainly be one way to resolve this issue.

That said, now that we have `sg.datasets`, it could be an easy way for a docker-familiar user to get a Jupyter Lab environment started and running the demos.

**Comment by yvonnegh** [comment]
If target market is data scientists, not sure if anyone is using our Docker image.
Metrics from docker hub are not useful to see what's happening.

Could discuss whether we stop publishing Docker image and then do it properly.
