### ISSUE TITLE
Add download links to demo notebooks on readthedocs

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1390]
### Description

When looking at our demo notebooks inside documentation on readthedocs (added for #1279), it would be useful to be able to directly download the notebook.

As an example, see scikit-learn, eg: https://scikit-learn.org/stable/auto_examples/plot_changed_only_pprint_parameter.html#sphx-glr-auto-examples-plot-changed-only-pprint-parameter-py

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by timpitman** [comment]
We're using nbsphinx plugin to embed notebooks inside docs, and it doesn't appear to support this.

The example above from scikit-learn uses a different plugin https://sphinx-gallery.github.io/stable/index.html which actually bundles files for download, but doesn't support Jupiter notebooks as input.

**Comment by kjun9** [comment]
Another approach might be to just include a link in the notebook that points to itself on github (i.e. update format notebook script to put in the link) and the user can do a "save as" on that?

**Comment by timpitman** [comment]
Adding a link to the notebook itself is a good idea, however I had a look and one problem is that GitHub doesn't allow direct download - clicking such a link opens the notebook source in a browser rather than just downloading it, eg: https://raw.githubusercontent.com/stellargraph/stellargraph/master/demos/basics/loading-networkx.ipynb

**Comment by kjun9** [comment]
Yeah I think we can't get around that unless we also host all our demos somewhere other than github. Maybe something like below is not terrible?:

*View the notebook or download via the "Save Link as..." option:* [loading-networkx.ipynb](https://raw.githubusercontent.com/stellargraph/stellargraph/master/demos/basics/loading-networkx.ipynb)

**Comment by huonw** [comment]
I think the `ipynb` files are already included (maybe by nbsphinx or maybe by nbsphinx-link?) in the Sphinx output; for instance, https://stellargraph.readthedocs.io/en/latest/demos/basics/loading-networkx.ipynb looks correct to me.

We can then probably use use `nbsphinx_prolog` to insert a download button (https://nbsphinx.readthedocs.io/en/0.6.1/prolog-and-epilog.html). Something involving `docname`, I guess.

> The example above from scikit-learn uses a different plugin https://sphinx-gallery.github.io/stable/index.html which actually bundles files for download, but doesn't support Jupyter notebooks as input (only specially-formatted .py files)

nbsphinx seems to have some sort of gallery support too: https://nbsphinx.readthedocs.io/en/0.6.1/subdir/gallery.html

**Comment by yvonnegh** [comment]
High priority, want this process to be seamless and possibly pretty straightforward.
