### ISSUE TITLE
Unclear ValueError message in FullBatchGenerator with sparse+ppnp

### ISSUE THREAD

**Issue by thatlittleboy** [stellargraph/stellargraph#1410]
### Describe the bug

There is a check for the erroneous combination of input arguments of `FullNodeGenerator(..., sparse=True, method='ppnp')` that raises a ValueError (`mapper/full_batch_generator.py`):
```py
        elif self.method in ["ppnp"]:
            if self.use_sparse:
                raise ValueError(
                    "use_sparse=true' is incompatible with 'ppnp'."
                    "Set 'use_sparse=True' or consider using the APPNP model instead."
                )
            self.features, self.Aadj = PPNP_Aadj_feats_op(
                features=self.features,
                A=self.Aadj,
                teleport_probability=self.teleport_probability,
            )
```

I have 2 (+1/2) issues/questions regarding the error message:
1. The inconsistency of checking `use_sparse==True` & raising ValueError, and then suggesting the end-user to set `use_sparse=True`. I haven't read up on the algorithm yet (so I could be way off-base here), but from the code, I am guessing the suggestion should be `use_sparse=False`?
1. The end-user has no (apparent) control over `use_sparse` as a variable, only the `sparse` argument of the `FullBatchGenerator` etc. I know there is a logic to check for tf backend, but do you think it would be more reasonable to have the error message read `Set 'sparse=False' or...` instead?

And finally, a minor gripe regarding the formatting of the error message (see screenshot below): no space between the period and the beginning of the next word, as in "...'ppnp'.Set ...".
(There are a couple other cases [e.g. [description here](https://stellargraph.readthedocs.io/en/latest/api.html#stellargraph.datasets.IAEnronEmployees)] like these in the docs and code-base, but that's unrelated to this issue.)

### To Reproduce

A minimal example:

```py
import stellargraph as sg
import pandas as pd
import numpy as np

node_feats = np.random.random(size=(3, 4))
nodes = pd.DataFrame(node_feats, index=range(3))
edges = pd.DataFrame({'source': [0, 1], 'target': [1, 2]})
G = sg.StellarGraph(nodes={'n0': nodes}, edges=edges)

gen = sg.mapper.FullBatchNodeGenerator(G, method='ppnp', sparse=True)
```

### Observed behavior

<img width="1055" alt="error stacktrace" src="https://user-images.githubusercontent.com/30731072/80661781-396db100-8ac2-11ea-9c0f-f3bf611a8afe.png">

### Expected behavior

Described above.

### Environment

Currently still present in 1cca6b6c (develop HEAD), py 3.6.8

---

<sub>
ps.
Thank you for all the work that you guys do: I really respect the team's effort in maintaining the project to such a high standard, and making it so easy for others to contribute. Cheers. :)
</sub>

**Comment by kieranricardo** [comment]
Hi @thatlittleboy, thanks for taking the time to file another issue, you're smashing them out!

I think you're right on both fronts:

1. Yeah it should be `use_sparse=False`
2. We should direct users to change the `sparse` argument in `FullBatchGenerator`

Do you want to file a PR for this one?

**Comment by thatlittleboy** [comment]
@kieranricardo Thank you for the guidance. Yes, I will try to make the edits and submit a PR tonight, if not later this week(end). :smiley:

**Comment by kieranricardo** [comment]
Great! I'll assign you to the issue and don't hesistate to ask any questions :smiley:

<sub>
ps.
Thankyou, this made our day. We really appreciate your feedback and contributions :) 
</sub>

**Comment by huonw** [comment]
For the error messages we've been progressively moving towards a somewhat formulaic format, like `<parameter name>: expected <description of good value>, found <bad value>`. In this case, it might be something like `sparse: method="ppnp" requires 'sparse=False', found 'sparse=True' (consider using the APPNP model for sparse support)`.

As an example of this format, consider the `node_type` line in the same class:

```python
        node_type = G.unique_node_type(
            "G: expected a graph with a single node type, found a graph with node types: %(found)s"
        )
```
