### ISSUE TITLE
Add GCN-LSTM demo to CI

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1424]
### Description

GCN-LSTM demo needs to be tested in Buildkite.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by yvonnegh** [comment]
There's a PR already for this.
