### ISSUE TITLE
Spatio-temporal demo isn't indexed

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1427]
### Describe the bug

The GCN-LSTM demo in https://github.com/stellargraph/stellargraph/tree/38eee704adbd6fa39084a8519692092146dffdef/demos/spatio-temporal doesn't appear in the various locations we discuss demos:

- it's not published on Read the Docs via an `nblink` file (as in https://github.com/stellargraph/stellargraph/pull/1279)
- it doesn't appear in the "Find an algorithm for a task" section https://stellargraph.readthedocs.io/en/latest/demos/index.html#find-algorithms-for-a-task
- it doesn't appear in the per-algorithm table https://stellargraph.readthedocs.io/en/latest/demos/index.html#find-a-demo-for-an-algorithm

**Comment by yvonnegh** [comment]
Folder doesn't appear in read the docs.
Isn't indexed in tables.

High priority - this is a key demo of 1.0
