### ISSUE TITLE
Nested demo folders are weird on read the docs

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1428]
### Describe the bug

Some of our demos are structured in subfolders, which leads to a slightly peculiar and complicated display on Read the Docs, e.g.: https://stellargraph.readthedocs.io/en/latest/demos/node-classification/index.html#table-of-contents

![image](https://user-images.githubusercontent.com/1203825/80775303-98a2f280-8ba2-11ea-847b-f7db1123ca55.png)

We could remove an extra layer of links by removing the subfolders.

This applies to:

- node classification
- link prediction
- interpretability

**Comment by yvonnegh** [comment]
Maybe worth rearranging on ReadTheDocs before they start linking to them.

But divergence between ReadTheDocs and Git repo....

Note there are some links to Notebook CI blogpost..
