### ISSUE TITLE
FullBatchGenerator still references StellarGraphBase in the Docs

### ISSUE THREAD

**Issue by thatlittleboy** [stellargraph/stellargraph#1436]
### Describe the bug

The docstring for both `FullBatchNodeGenerator` and `FullBatchLinkGenerator` reference `G`'s type to be a `StellarGraphBase`. This then appears in the ReadTheDocs documentation, making it confusing for the end-user.

<img width="728" alt="readthedocs with StellarGraphBase" src="https://user-images.githubusercontent.com/30731072/80784010-2b955a00-8bae-11ea-8c57-b8f28a8afb5a.png">

Only these 2 classes continue to reference `StellarGraphBase`; all others like UnsupervisedSampler, ClusterNodeGenerator etc. have transitioned to specifying StellarGraph as `type(G)`.

### To Reproduce

 Do a Ctrl+F search for `StellarGraphBase` on Read the Docs API page. Only 2 results, which correspond to the 2 aforementioned classes.

### Observed behavior

`type(G)` reads `StellarGraphBase`.

### Expected behavior

`type(G)` to read `StellarGraph` to be consistent with the rest of the documentation. Also, as far as I can see, `StellarGraphBase` has already been removed from the code base.

### Environment

StellarGraph develop HEAD 6da46b8

----

I can make a PR to fix this if the team agrees with the discussion above. Thanks.

**Comment by huonw** [comment]
Yeah, StellarGraphBase was removed in #501, and `StellarGraph` is indeed the replacement. 👍
