### ISSUE TITLE
Wrong README title for Calibration demos

### ISSUE THREAD

**Issue by thatlittleboy** [stellargraph/stellargraph#1443]
### Describe the bug

The title / heading on the [`demos/calibration/README.md`](https://github.com/stellargraph/stellargraph/tree/9506f9351718399cc561faca184d821e661c798a/demos/calibration) file is wrong -- it reads "Ensemble learning for graph neural network algorithms", likely a copy-paste error:

<img width="983" alt="readme" src="https://user-images.githubusercontent.com/30731072/80858901-45f33480-8c8f-11ea-8a9e-638ebf120605.png">

This error is also visible from the Read the Docs demos. There are 2 "Ensemble learning ..." pages as you can see from the sidebar ToC.

<img width="1116" alt="readthedocs" src="https://user-images.githubusercontent.com/30731072/80858918-658a5d00-8c8f-11ea-8de3-c8557de18225.png">

--- 

<s>This should be a straightforward fix -- I'll raise a PR for this soon.</s>

My original plan was to change the title on both README.md and the index.txt manually, but I realized there's an ongoing PR #1433 to address the RtD / README duplication issue (#1419). 
Maybe this can wait till after that PR is merged in.

**Comment by timpitman** [comment]
Thanks @thatlittleboy for such a clear bug report! I'm going to add a small fix ahead of #1433, https://github.com/stellargraph/stellargraph/pull/1453
