### ISSUE TITLE
MaxPoolingAggregator and AttentionalAggregator are missing from Read the Docs

### ISSUE THREAD

**Issue by thatlittleboy** [stellargraph/stellargraph#1445]
### Describe the bug

`MaxPoolingAggregator` and `AttentionalAggregator` are missing from Read the Docs documentation.

Only the references inside GraphSAGE/DirectedGraphSAGE docstring are found.

<img width="1132" alt="missing maxpoolingaggregator" src="https://user-images.githubusercontent.com/30731072/80898748-9cb54880-8d39-11ea-921b-8c8d72ae1df5.png">

### To Reproduce

Search for `MaxPoolingAggregator` and `AttentionalAggregator` on the API page.

### Environment

Stellargraph develop HEAD 9506f93

---

I'm not well-versed in RtD/sphinx (yet), but a quick search through the codebase seems to point at the syntax for `autoclass` being wrong for these 2 classes inside `docs/api.txt`,

https://github.com/stellargraph/stellargraph/blob/9506f9351718399cc561faca184d821e661c798a/docs/api.txt#L42-L52

That is, it should be a double colon instead of single colon after `autoclass`.

**Comment by huonw** [comment]
Yeah, I think you're correct about the colon vs double-colon. 👍 Great catch.
