### ISSUE TITLE
GCN-LSTM notebook on readthedoc has some poorly formatted text

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1492]
### Describe the bug

The "References" list is poorly formatted at the beginning of the notebook.

### To Reproduce

1. Go to https://stellargraph.readthedocs.io/en/latest/demos/time-series/gcn-lstm-time-series.html
2. Scroll down to the references list

### Observed behavior

![image.png](https://images.zenhubusercontent.com/5ad3f71c4b5806bc2bcf28ff/ec9b1b7f-595a-49fb-802c-64426ddd9a35)

### Expected behavior

Should be formatted correctly

### Environment

Browser: Chrome
Stellargraph: latest documentation

**Comment by huonw** [comment]
Also:

> This is how it works: * Starting from the beginning of the timeseries, we take the first 10 speed records as the 10 input features and the speed 12 timesteps head (60 minutes) as the speed we want to predict. * Shift the timeseries by one timestep and take the 10 observations from the current point as the input feartures and the speed one hour ahead as the output to predict. * Keep shifting by 1 timestep and picking the 10 timestep window from the current time as input feature and the speed one hour ahead of the 10th timestep as the output to predict, for the entire data. * The above steps are done for each sensor.
