### ISSUE TITLE
Demo notebook navigation would be easier with more information in side-bar ToC

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1499]
### Describe the bug

We have quite a few notebooks, with logically distinct subsections. It might be nice to have this represented in the sidebar, so that someone can more easily jump to adjacent notebooks for a task or to a different section.

For instance, in the Pandas notebook, it'd be nice to be able to see the various sections to jump back to them, and see the NetworkX notebooks (and so on):

![image](https://user-images.githubusercontent.com/1203825/81035753-b5f7f980-8edf-11ea-89e4-501940adb709.png)

**Comment by yvonnegh** [comment]
Waiting for new release of external tool.
