### ISSUE TITLE
Adding nodes or edges to a StellarGraph doesn't set a default type

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#151]
### Description
When creating a StellarGraph from a NetworkX graph we fill in the node and edge types with defaults when not specified. When adding nodes/edges to a StellarGraph object we are required to specify this type otherwise it will not be filled.

e.g.
```
    G = StellarGraph()
    elist = [(1, 2), (2, 3), (1, 4), (3, 2)]
    G.add_edges_from(elist)
    print(G.info())
```

The `G.info()` command will fail with the following error:
```
ValueError: All nodes should have a type set in the 'label' attribute.
```

Additionally, ML methods will fail as there are no node or type attributes set.

### Done Checklist (Bug)
- [ ] Bug fixed
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by flawnson** [comment]
Hi, I'm actually facing this issue right now. I'm working on a project that turns urban maps into graphs and uses machine learning to predict traffic flow. I used PyTorch Geometric for a while but decided to try StellarGraph for your link prediction functions that you have implemented.

I already have my graph in networkx graph format with all the attributes (both node and edge), but I'm having trouble turning the graph into Stellargraph native format. The error says:

"TypeError: Node type not found in importing feature vectors!"

I'm not entirely sure what node type is refering to. Any thoughts on how to get around or fix this?

**Comment by youph** [comment]
@adocherty can we provide a quick fix for the above, before the new StellarGraph class is implemented?

**Comment by geoffj-d61** [comment]
To my quick scan of the code containing that error, it looks like the type information is assumed as the first element of each datum. Not sure how long it would take to unwind all of the assumptions made.

**Comment by geoffj-d61** [comment]
Also, the block of code given at the top of this ticket actually works without error.

**Comment by flawnson** [comment]
Thanks I just used the method used for the example in the documentation to get around the type problem, would be nice to have a seamless transition from NetworkX to StellarGraph though. I'll look into it.

Also curious if StellarGraph has the capability to accept edge attributes in a similar way as it does node attributes. It would be very useful for Urban data science/Infrastructure applications as well as for molecular representation.

**Comment by youph** [comment]
> Also, the block of code given at the top of this ticket actually works without error.

If you do `print(G.info())` after that block of code, you get the error.

**Comment by youph** [comment]
> Also curious if StellarGraph has the capability to accept edge attributes in a similar way as it does node attributes. It would be very useful for Urban data science/Infrastructure applications as well as for molecular representation.

This is in our to-do list :)

**Comment by adocherty** [comment]
The error you are reporting is not connected with this issue. When you create a `stellargraph` not from an existing NetworkX object the node type is created automatically. This issue is describing problems when creating an empty `stellargraph` object then adding nodes & edges without type information.

Your original error is triggered when trying to import the feature vectors that match the nodes in the graph.  In particular, it looks like you are trying to specify node features as a list. Could you tell us more about how you are trying to feed node features to the `stellargraph` object?

It is best to specify node features as a pandas `DataFrame` where the index is the Node ID (which must exist in the NetworkX graph).

For example:
```
import stellargraph as sg
import pandas as pd

G = nx.Graph()
elist = [(1, 2), (2, 3), (1, 4), (3, 2)]
G.add_edges_from(elist)

features = pd.DataFrame([[1,0,1],[0,1,1],[1,1,0],[1,0,1]], index=[1,2,3,4])
Gs = sg.StellarGraph(G, node_features=features)
```
Note that the `features` DataFrame has an index with the same IDs as the nodes in the graph.

If you continue to experience this error, please give us more details of how you are specifying the features when you create the `stellargraph` object.

**Comment by geoffj-d61** [comment]
@adocherty, I got confused between missing node labels and missing edge labels - I will retract my addition. I have just been reading the `StellarGraphBase.__init__` method to see the defaults assigned. I will keep following the code trail. Is it plausible to simply use a `get` with a default whenever we want a type?
