### ISSUE TITLE
Multivariate time-series forecasting for GCN-LSTM

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1527]
### Description

Can we use Keras's existing multi-variate LSTM?

### User Story

**As** a ...

**I want to** [accomplish some things]

**So that** [achieve a larger goal]

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
One approach here might be generalising the transposition for graph convolution to include some reshaping to run graph convolution on `time steps * variate dimension`:

https://github.com/stellargraph/stellargraph/blob/ee3bd69435ba0a7b630dd0ae566f095c99167e66/stellargraph/layer/gcn_lstm.py#L178
