### ISSUE TITLE
Fill the docstring of from_epgm() in /data/loader.py

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#153]
### Description
The docstring for `from_epgm()` function in `loader.py` is currently a stub; it needs to be populated.

### Done Checklist (Development)
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Branch and Pull Request pass integration tests on CI
- [x] Code well commented

**Comment by adocherty** [comment]
Fixed in PR #230
