### ISSUE TITLE
Improve demo indexing for keras Node2Vec notebooks

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1534]
### Description

With https://github.com/stellargraph/stellargraph/pull/536 we now have two different versions of the `node2vec` algorithm being demoed with notebooks - `gensim` vs stellargraph components. 

Currently: 
* the top-level demo summary table shows these as two separate algorithms, but this could be improved to show that they are in fact one algorithm (maybe should be in one row with multiple links in a cell?)
* they're missing from the task-specific demo tables, but should be included in a similar way to whatever approach is taken for the top-level demo table

**Comment by huonw** [comment]
Another option would be to instead remove the `gensim` version?

**Comment by daokunzhang** [comment]
> Another option would be to instead remove the `gensim` version?

Hi @huonw ,

I think the `genesim` version is still necessary. As it is built on the original word2vec C implementation, it is much faster than the keras implementation and it can handle much larger dataset. As our metapath2vec implementation and the link prediction with random walks demo still rely on the `gensim` word2vec, I think it is better to preserve a `gensim` node2vec demo, to make a consistently. 

Best regards,
Daokun
