### ISSUE TITLE
Splitter returns node IDs as strings and fails when labels are numeric

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#155]
### Description
1. If there are any strings in the class labels then the entire `y` array will be up-converted by numpy to strings. The splitter will then split the node IDs and return them all as strings. However, if the node IDs are not strings this will fail - even worse if they are mixed then the calling code will not be able to know how to convert them back to the actual node IDs.

e.g.
```
nodes = [1,2,3,4,5,6,"7",8]; labels = [1,1,1,0,0,0,0,0]
y = np.array(list(zip(nodes, labels)))
NodeSplitter().train_test_split(p=2, y=y, test_size=2)
(array([['4', '0'], ['8', '0'], ['2', '1'], ['1', '1']], dtype='<U21'), 
 array([['3', '1'], ['5', '0']], dtype='<U21'), 
array([['7', '0'], ['6', '0']], dtype='<U21'), 
array([], shape=(0, 2), dtype='<U21'))
```
2. If the node IDs are numeric and the labels are numeric the code fails:

e.g.
```
nodes = [1,2,3,4,5,6,7,8]; labels = [1,1,1,0,0,0,0,0]
y = np.array(list(zip(nodes, labels)))
NodeSplitter().train_test_split(p=2, y=y.astype('str'), test_size=2)
(array([['4', '0'], ['8', '0'], ['2', '1'], ['1', '1']], dtype='<U21'), 
 array([['3', '1'], ['5', '0']], dtype='<U21'), 
array([['7', '0'], ['6', '0']], dtype='<U21'), 
array([], shape=(0, 2), dtype='<U21'))

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-74-054fab109102> in <module>()
----> 1 s.train_test_split(p=2, y=y, test_size=2)

~/Code/stellar-ml/stellar/data/node_splitter.py in train_test_split(self, y, p, method, test_size, train_size, seed)
    361
    362         if method == "count":
--> 363             return self._split_data(y, p, test_size)
    364         elif method == "percent":
    365             n_unlabelled_points = np.sum(y[:, 1] == UNKNOWN_TARGET_ATTRIBUTE)

~/Code/stellar-ml/stellar/data/node_splitter.py in _split_data(self, y, nc, test_size)
    462             if ind[0].size <= nc:
    463                 # too few labeled examples for class so use half for training and half for testing
--> 464                 ind_selected = np.random.choice(ind[0], ind[0].size // 2, replace=False)
    465             else:
    466                 ind_selected = np.random.choice(ind[0], nc, replace=False)

mtrand.pyx in mtrand.RandomState.choice()

ValueError: a must be non-empty
```

### Done Checklist (Bug)
- [ ] Bug fixed
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by youph** [comment]
@PantelisElinas could you please check that this is still relevant for node splitter, and whether this happens for edge splitter, and decide whether this should be fixed, moved to ice box, or closed.

**Comment by youph** [comment]
@PantelisElinas if none of our demos use the old splitter classes, this can be closed.

**Comment by huonw** [comment]
In addition to the comments, `NodeSplitter` no longer exists (#885/#887), so moving this to Done.
