### ISSUE TITLE
Have consistent link back to GitHub on Read the Docs

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1552]
### Description

Our read the docs doesn't include any _great_ links back to the GitHub repo. Some documents include a link to https://github.com/stellargraph/stellargraph and there's an "Edit on Github" in the top right of each page:

![image](https://user-images.githubusercontent.com/1203825/81632768-70db4680-944e-11ea-8dc2-05028333a75e.png)

This means it's difficult for users to return to github to log an issue / provide feedback. (and give us stars)

However, these have problems like being unreliable (not every page will have a manual link to GitHub) and not being that clear. If we insert a link (or more) automatically into every page, we get both consistency and clarity.

Some options:

- https://pytest-benchmark.readthedocs.io/en/latest/ "Fork me on Github" banner on the right
- https://black.readthedocs.io/en/stable/ https://requests.readthedocs.io/en/master/ "Github stars" button in the navigation column
- something else?

**Comment by timpitman** [comment]
Some of those pages linked above simply use options in the alabaster theme: https://alabaster.readthedocs.io/en/latest/customization.html

**Comment by huonw** [comment]
In addition to adding banners that alabaster does:

- watch/star button: https://github.com/bitprophet/alabaster/blob/3b68afcfe55a80508254b22904294100a160e6a7/alabaster/about.html#L20-L23
- top-right "sash" banner: https://github.com/bitprophet/alabaster/blob/3b68afcfe55a80508254b22904294100a160e6a7/alabaster/layout.html#L102-L106

I thought the little "Getting help" section on the side of <https://www.fatiando.org/verde/latest/> was pretty nice. The source code makes this look relatively simple to configure via `html_context`: https://github.com/fatiando/verde/blob/644037ee5f6890f54430289eac5f5b0f654140f6/doc/conf.py#L110-L132

**Comment by huonw** [comment]
I've opened #1605 that just adds the buttons/banners to our existing theme.

> The source code makes this look relatively simple to configure via html_context

It turns out this is actually just feeding into their template customisations: https://github.com/fatiando/verde/blob/644037ee5f6890f54430289eac5f5b0f654140f6/doc/_templates/layout.html
