### ISSUE TITLE
Improve Neo4J GraphSAGE sampler

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#1568]
### Description

We should evaluate the current GraphSAGE NEO4J sampler and improve it, eg:
* better Cypher sampling code
* not requiring the features to be in-memory

### User Story

**As** a ...

**I want to** [accomplish some things]

**So that** [achieve a larger goal]

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
This may have some overlap with the `Neo4jStellarGraph` @kieranricardo introduces in #1567.
