### ISSUE TITLE
Build up install procedure for stellar-ml

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#164]
### Description
We need to be able to install the library easily. This will involve writing and testing the:
- setup.py (build + install) procedure
- pip install procedure
- dependencies

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Peer Install Review Performed
- [ ] Tested on clean machines + environments

**Comment by youph** [comment]
@adocherty can this be moved to Done or Closed?
