### ISSUE TITLE
Loading demos weren't all updated to link to NumPy demo

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1640]
### Describe the bug

*A clear and concise description of what the bug is.*

### To Reproduce

https://stellargraph.readthedocs.io/en/latest/demos/basics/loading-pandas.html

### Observed behavior

No search results for "numpy".

### Expected behavior

At least the section that refers to NetworkX and Neo4j should be updated in the Pandas demo and the other ones too.

### Environment

https://github.com/stellargraph/stellargraph/commit/e3bf444eea5371a7c43fadd05a35c33d05d9fedd

### Additional context

N/A

**Comment by timpitman** [comment]
Would it be more future proof to just link back to the base documentation rather than individual demos?

**Comment by huonw** [comment]
Probably.
