### ISSUE TITLE
high is out of bounds for int32. 

### ISSUE THREAD

**Issue by flowingrain** [stellargraph/stellargraph#1668]
In knowledge_graph.py,
`np.random.RandomState, self._global_rs.randint(2 ** 32) `
but the maximum of positive int32 integer is 2**-1

**Comment by flowingrain** [comment]
File "<ipython-input-3-7251035422b2>", line 1, in <module>
    runfile('C:/Users/flogw/Desktop/mypaper/Signed network influence maximization/Experiments/StellarGraph/DistMult-test.py', wdir='C:/Users/flogw/Desktop/mypaper/Signed network influence maximization/Experiments/StellarGraph')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/flogw/Desktop/mypaper/Signed network influence maximization/Experiments/StellarGraph/DistMult-test.py", line 51, in <module>
    wn18_train, negative_samples=negative_samples_each, shuffle=True#negative_samples (int, optional) – the number of negative samples to generate for each positive edge.

  File "D:\Anaconda3\lib\site-packages\stellargraph\mapper\knowledge_graph.py", line 102, in flow
    seed=seed,

  File "D:\Anaconda3\lib\site-packages\stellargraph\mapper\knowledge_graph.py", line 137, in __init__
    np.random.RandomState, self._global_rs.randint(2 ** 32)#high is out of bounds for int32. int32 范围-2**31～2**31-1

  File "mtrand.pyx", line 990, in mtrand.RandomState.randint

ValueError: high is out of bounds for int32

**This happens when I tried to run DistMult for link prediction task, with code from [DistMult](https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/distmult-link-prediction.html)**

`from stellargraph import datasets, utils`
`from tensorflow.keras import callbacks, optimizers, losses, metrics, regularizers, Model`
`import numpy as np`
`import pandas as pd`
`from stellargraph.mapper import KGTripleGenerator`
`from stellargraph.layer import DistMult`

`epochs = 300`
`embedding_dimension = 100`
`negative_samples_each = 0`

`wn18 = datasets.WN18()`
`print(wn18.description)`
`wn18_graph, wn18_train, wn18_test, wn18_valid = wn18.load()`
`print(wn18_train)`

`print(wn18_graph.info())`


#[7]:
wn18_gen = KGTripleGenerator(
    wn18_graph, batch_size=len(wn18_train) // 10  # ~10 batches per epoch. //表示整数除法
)
wn18_distmult = DistMult(
    wn18_gen,
    embedding_dimension=embedding_dimension,
    embeddings_regularizer=regularizers.l2(1e-7),
)
wn18_inp, wn18_out = wn18_distmult.in_out_tensors()
wn18_model = Model(inputs=wn18_inp, outputs=wn18_out)
wn18_model.compile(
    optimizer=optimizers.Adam(lr=0.001),
    loss=losses.BinaryCrossentropy(from_logits=True),
    metrics=[metrics.BinaryAccuracy(threshold=0.0)],
)

#[8]:
wn18_train_gen = wn18_gen.flow(
    wn18_train, negative_samples=negative_samples_each, shuffle=True#negative_samples (int, optional) – the number of negative samples to generate for each positive edge.
)
wn18_valid_gen = wn18_gen.flow(wn18_valid, negative_samples=negative_samples_each)

#[9]:
wn18_es = callbacks.EarlyStopping(monitor="val_loss", patience=50)
wn18_history = wn18_model.fit(
    wn18_train_gen,
    validation_data=wn18_valid_gen,
    epochs=epochs,
    callbacks=[wn18_es],
    verbose=0,
)

  
#[10]:
utils.plot_history(wn18_history)

#[11]:
wn18_smaller_gen = KGTripleGenerator(wn18_graph, batch_size=5000)
wn18_raw_ranks, wn18_filtered_ranks = wn18_distmult.rank_edges_against_all_nodes(
    wn18_smaller_gen.flow(wn18_test), wn18_graph
)

#[12]:
# helper function to compute metrics from an array of ranks
def results_as_dataframe(mrr, hits_at_10):
    return pd.DataFrame(
        [(mrr, hits_at_10)], columns=["mrr", "hits at 10"], index=["filtered"],
    )

def summarise(ranks):
    return results_as_dataframe(np.mean(1 / ranks), np.mean(ranks <= 10))

#13
summarise(wn18_filtered_ranks)

#[14]:
results_as_dataframe(0.83, 0.942)

**Comment by huonw** [comment]
Ah, thanks. That's very helpful!

I guess you're running on a 32-bit machine (`print(np.int_)` says `<class 'numpy.int64'>` for me, what does it say for you?), which indeed would fail here.

This should be an easy fix. I'll do it now.

(BTW, your comment was very hard to read. I edited it to use fenced code blocks with ```` ``` ```` (see the "code" tab of https://guides.github.com/features/mastering-markdown/#examples ), which makes it much easier to understand. I hope that's ok.)

**Comment by flowingrain** [comment]
> print(np.int_)

Yes, I get 

> <class 'numpy.int32'>
after print operation, maybe I haven't installed the right version of numpy library. Thank you for your patience.

**Comment by huonw** [comment]
> This should be an easy fix. I'll do it now.

https://github.com/stellargraph/stellargraph/pull/1671 contains the fix. It's a patch directly on top of 1.1.0. It can be installed with `pip install git+https://github.com/stellargraph/stellargraph.git@ b08348d94c593ac02c1445621884029c33a276ca` (b08348d94c593ac02c1445621884029c33a276ca is the commit in that patch).

An alternative would be to upgrade to a 64-bit version of NumPy and/or Python (wherever the problem is).
