### ISSUE TITLE
AttributeError: 'Cora' object has no attribute 'load'

### ISSUE THREAD

**Issue by yashwanth033** [stellargraph/stellargraph#1683]
When trying to load Graph and node subjects  from CORA dataset, throwing AttributeError: 'Cora' object has no attribute 'load'.
[https://stellargraph.readthedocs.io/en/stable/demos/embeddings/graphsage-unsupervised-sampler-embeddings.html#Extracting-node-embeddings](url)

from stellargraph import datasets
dataset = datasets.Cora()
display(HTML(dataset.description))
G, node_subjects = dataset.load()

### Observed behavior

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-69-626693cad27a> in <module>
----> 1 G, node_subjects = dataset.load()

AttributeError: 'Cora' object has no attribute 'load'

### Environment

Operating system: Windows 10 enterprise

Python version: 3.7.6

Package versions: stellargraph==0.10.0, tensorflow==1.14.0

**Comment by huonw** [comment]
Hi @yashwanth033, thanks for filing an issue.

This is a version mismatch issue: the notebook on Read the Docs is designed for StellarGraph version 1.1.0, but you're using version 0.10.0. There's two options here:

- upgrade to a newer StellarGraph; this will require updating TensorFlow, and so may be a bit complicated, but it will bring you a lot of optimisations and improvements that have happened in 0.11, 1.0 and 1.1 (see https://github.com/stellargraph/stellargraph/releases for more details on each)
- use the version of the notebook from 0.10.0: 
  - GitHub: https://github.com/stellargraph/stellargraph/blob/v0.10.0/demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb
  - Nicer rendering: https://nbviewer.jupyter.org/github/stellargraph/stellargraph/blob/v0.10.0/demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb
  - Download link: https://raw.githubusercontent.com/stellargraph/stellargraph/v0.10.0/demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb

Does that help?

**Comment by yashwanth033** [comment]
Thank you for your help. That helps a lot.
