### ISSUE TITLE
Consider adding optional regularisation on the weights for GraphSage and HinSage

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#172]
### Description
The GraphSage and HinSage models can easily get over-parameterised (e.g., a 2-layer GraphSage model for node classification on cora dataset has ~94k parameters!), so we might want to add optional weight regularisation to the models, e.g., L1.

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo
- [ ] Team demo

**Comment by adocherty** [comment]
This is superseded by #469.
