### ISSUE TITLE
Make the EdgeSplitter return StellarGraph instead of Networkx graph

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#174]
### Description
Currently EdgeSplitter returns a networkx graph, which then needs to be converted to StellarGraph again. It should accept and return StellarGraph graphs.

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by huonw** [comment]
This task is now more important that we're moving away from NetworkX, so I'm working on it under the umbrella of #662.
