### ISSUE TITLE
HinSAGE meanpooling/maxpooling aggregators

### ISSUE THREAD

**Issue by silkeplessers** [stellargraph/stellargraph#1787]
I was wondering if it would be possible to implement the meanpooling and maxpooling aggregators for HinSAGE. GraphSAGE already has these aggregators implemented and in many cases these seem to outperform the mean aggregator so I think HinSAGE also could benefit from these aggregator functions. Is there any reason these are not implemented yet (maybe it's impossible or are there any difficulties)?

Kind regards

**Comment by huonw** [comment]
I think this should be possible. It could even be done outside the library and passed into the `HinSAGE` class via the `aggregator` argument. One way to do this would be to copy the `MeanHinAggregator` code and make appropriate changes (this may be quite fiddly, though):

https://github.com/stellargraph/stellargraph/blob/ec132647e5cf43ff683e3f2e72e18ac6daa98202/stellargraph/layer/hinsage.py#L41-L216
