### ISSUE TITLE
RelationalFullBatchNodeGenerator does not work with heterogenous entity graphs

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [stellargraph/stellargraph#1808]
### Describe the bug

I may well be asking something of the class for which it is not intended, but following [the docs](https://stellargraph.readthedocs.io/en/stable/demos/embeddings/deep-graph-infomax-embeddings.html) I understand that `RGCN` can be used for heterogenous entity graphs, but when I attempt to create a generator for it using `RelationalFullBatchNodeGenerator` and a heterogenous entity graph, I get the following error:

```
ValueError: G: expected one node type, found 'bar', 'foo'
```

Is this simply the wrong type of generator to use?

### To Reproduce

```
# coding: utf-8

import numpy as np
import pandas as pd
from stellargraph import IndexedArray, StellarDiGraph
from stellargraph.mapper import (
    RelationalFullBatchNodeGenerator,
    RelationalFullBatchNodeSequence,
)

foo_nodes = IndexedArray(np.array([[-1]]), index=["a"])
bar_nodes = IndexedArray(
    np.array([[0.4, 100], [0.1, 200], [0.9, 300]]), index=["b", "c", "d"]
)

horizontal_edges = pd.DataFrame(
    {"source": ["a", "c"], "target": ["b", "d"]}, index=[0, 2]
)
vertical_edges = pd.DataFrame(
    {"source": ["b", "d"], "target": ["c", "a"]}, index=[1, 3]
)
diagonal_edges = pd.DataFrame({"source": ["a"], "target": ["c"]}, index=[4])

orientation_edges = pd.DataFrame(
    {
        "source": ["a", "b", "c", "d", "a"],
        "target": ["b", "c", "d", "a", "c"],
        "type": ["h", "v", "h", "v", "d"],
    }
)

G = StellarDiGraph(
    {"foo": foo_nodes, "bar": bar_nodes},
    {"h": horizontal_edges, "v": vertical_edges, "d": diagonal_edges},
)
print(G.info())
generator = RelationalFullBatchNodeGenerator(G)
```

### Observed behavior

```
StellarDiGraph: Directed multigraph
 Nodes: 4, Edges: 5

 Node types:
  bar: [3]
    Features: float64 vector, length 2
    Edge types: bar-h->bar, bar-v->bar, bar-v->foo
  foo: [1]
    Features: int64 vector, length 1
    Edge types: foo-d->bar, foo-h->bar

 Edge types:
    foo-h->bar: [1]
        Weights: all 1 (default)
        Features: none
    foo-d->bar: [1]
        Weights: all 1 (default)
        Features: none
    bar-v->foo: [1]
        Weights: all 1 (default)
        Features: none
    bar-v->bar: [1]
        Weights: all 1 (default)
        Features: none
    bar-h->bar: [1]
        Weights: all 1 (default)
        Features: none
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Documents/wellcome/grant-embedding/repro.py in <module>
     35 )
     36 print(G.info())
---> 37 generator = RelationalFullBatchNodeGenerator(G)

~/Documents/wellcome/grant-embedding/build/virtualenv/lib/python3.7/site-packages/stellargraph/mapper/full_batch_generators.py in __init__(self, G, name, sparse, transform, weighted)
    462         if len(node_types) != 1:
    463             raise ValueError(
--> 464                 f"G: expected one node type, found {comma_sep(sorted(node_types))}",
    465             )
    466

ValueError: G: expected one node type, found 'bar', 'foo'
```

### Expected behavior

I expect the generator to be successfully produced.

### Environment

Operating system: `Linux-4.15.0-117-generic-x86_64-with-debian-buster-sid`

Python version:

```
3.7.2 (default, Jul  3 2019, 11:00:30) 
[GCC 7.4.0]
```

Package versions:
<details>

```
absl-py==0.10.0
appdirs==1.4.4
astunparse==1.6.3
atpublic==2.0
backcall==0.2.0
black==20.8b1
bleach==3.2.0
blis==0.4.1
boto==2.49.0
boto3==1.14.63
botocore==1.17.63
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
click==7.1.2
colorama==0.4.3
commonmark==0.9.1
configobj==5.0.6
cryptography==3.1
cycler==0.10.0
cymem==2.0.3
Cython==0.29.21
decorator==4.4.2
dictdiffer==0.8.1
distro==1.5.0
docutils==0.15.2
dpath==2.0.1
dvc==1.7.2
Faker==4.1.3
flake8==3.8.3
flatten-dict==0.3.0
flufl.lock==3.2
ftfy==5.8
funcy==1.14
future==0.18.2
gast==0.3.3
gensim==3.8.3
gitdb==4.0.5
GitPython==3.1.8
google-auth==1.21.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grandalf==0.6
-e git+git@github.com:wellcometrust/grant-embedding.git@5b9cbe3e287141a756f262842cb94e4ef7f7bb4d#egg=grant_embeddings
grpcio==1.32.0
h5py==2.10.0
hdbscan==0.8.26
idna==2.10
importlib-metadata==1.7.0
ipdb==0.13.3
ipython==7.18.1
ipython-genutils==0.2.0
jedi==0.17.2
jeepney==0.4.3
jmespath==0.10.0
joblib==0.16.0
jsonpath-ng==1.5.2
Keras-Preprocessing==1.1.2
keyring==21.4.0
kiwisolver==1.2.0
llvmlite==0.34.0
Markdown==3.2.2
matplotlib==3.3.2
mccabe==0.6.1
murmurhash==1.0.2
mypy-extensions==0.4.3
nanotime==0.5.2
nervaluate==0.1.7
networkx==2.5
numba==0.51.2
numpy==1.19.2
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.2
parso==0.7.1
pathlib2==2.3.5
pathspec==0.8.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pkginfo==1.5.0.1
plac==0.9.6
ply==3.11
preshed==3.0.2
prompt-toolkit==3.0.7
protobuf==3.13.0
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.20
pydot==1.4.1
pyflakes==2.2.0
Pygments==2.7.0
pygtrie==2.3.2
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
readme-renderer==26.0
regex==2020.7.14
requests==2.24.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rfc3986==1.4.0
rich==6.2.0
rsa==4.6
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.2
SecretStorage==3.1.2
sentencepiece==0.1.91
shortuuid==1.0.1
shtab==1.3.1
six==1.15.0
smart-open==2.1.1
smmap==3.0.4
spacy==2.2.1
spacy-transformers==0.5.1
srsly==1.0.2
stellargraph==1.2.1
tabulate==0.8.7
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
text-unidecode==1.3
thinc==7.1.1
threadpoolctl==2.1.0
toml==0.10.1
torch==1.6.0
torchcontrib==0.0.2
tqdm==4.49.0
traitlets==5.0.4
transformers==2.0.0
twine==3.2.0
typed-ast==1.4.1
typer==0.3.2
typing-extensions==3.7.4.3
umap-learn==0.4.6
urllib3==1.25.10
voluptuous==0.11.7
wasabi==0.8.0
wcwidth==0.2.5
webencodings==0.5.1
wellcomeml==2020.9.0
Werkzeug==1.0.1
wrapt==1.12.1
zc.lockfile==2.0
zipp==3.1.0

```

</details>

**Comment by huonw** [comment]
Hi, thanks for getting in touch.

RGCN allows multiple edge types (that is, links or relationships), but only one node type (that is, entity, vertex). It is designed for knowledge graphs, which StellarGraph models as many nodes of a single type with all the actual information encoded in the edges. For instance, instead of node `a` having "type" `foo`, there might instead be a `foo` node, and an edge `a -has_type-> foo`.

Does that make sense?

**Comment by ivyleavedtoadflax** [comment]
Ah thanks @huonw I had not appreciated that. I've also been experimenting with HinSAGE for the same purpose, but the HinSAGE generator does allow multiple node types in the graph, although you specify a single head node type. Should I also be representing the knowledge graph as you have described here for the HinSAGE case?

**Comment by huonw** [comment]
As you've noted HinSAGE is more flexible because it allows multiple node types, but you're correct that only one node type can be chosen as the head node type for a given (node classification) task. The (features of) nodes of other types are only used as input to the model by aggregating neighbourhoods of the nodes of the chosen head node type.

As such, it's generally not necessary or appropriate to switch to do the same change for HinSAGE. However, I could imagine some cases where the node type is better modeled as a one-hot encoded node feature than as separate types, with all nodes of the same type.

Does that make sense?

**Comment by ivyleavedtoadflax** [comment]
Yes that makes a lot of sense. Thanks so much @huonw. I will close this issue.

**Comment by ivyleavedtoadflax** [comment]
Hi @huonw - just digesting your responses in a bit more detail, and realise I didn't totally understood.

> For instance, instead of node `a` having "type" `foo`, there might instead be a foo node, and an edge `a -has_type-> foo`.

In the above instance `a -has_type-> foo` looks like it as an edge between nodes `a` and `foo` which seems to contradict:

> as many nodes of a single type with all the actual information encoded in the edges

Is it the case that this edge is a self connecting edge `a --- has_type_foo ----> a`?

**Comment by huonw** [comment]
Ah no, the node types (in a `StellarGraph` sense) of `a` and `foo` would be the same in that example. For instance, a knowledge graph might be built like:

```python
edges = pd.DataFrame(
    [("a", "has_type", "foo"), ...], 
    columns=["source", "type", "target"]
)
StellarGraph(edges=edges, edge_type_column="type")
```

That is, both `a` and `foo` would be represented in the same way in the graph, even if they have very different meanings. That meaning would hopefully be captured by any algorithms used. For instance, if one was computing node embeddings with DistMult or ComplEx, the embeddings for `a` and `foo` would likely be different, because they have such different semantic meaning.

Does that help clarify?

**Comment by ivyleavedtoadflax** [comment]
Yes, many thanks @huonw  - I appreciate you taking the time to answer these questions :+1:
