### ISSUE TITLE
ValueError: edges['cites']: expected 'source', 'target', 'weight' columns, found:

### ISSUE THREAD

**Issue by Denkenwow** [stellargraph/stellargraph#1822]
How to solve this error ?

ValueError: edges['cites']: expected 'source', 'target', 'weight' columns, found: ('drug1',), ('drug2',)

**Comment by saustar** [comment]
@Denkenwow Assuming you are using pandas dataframe. Your columns name for you edge should be 'source' ,'target' and if you want to have weighted edges ,column name 'weight'. See [this](https://stellargraph.readthedocs.io/en/stable/demos/basics/loading-pandas.html) for reference

**Comment by huonw** [comment]
You can also set the column names to use as the source/target like `StellarGraph(..., source_column="drug1", target_column="drug2")`. The cell that constructs `square_first_second` shows this, in the notebook linked by @saustar: https://stellargraph.readthedocs.io/en/stable/demos/basics/loading-pandas.html

[The documentation for the `StellarGraph` class](https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.StellarGraph) gives a little more details too:

>  `stellargraph.StellarGraph(nodes=None, edges=None, *, is_directed=False, source_column='source', target_column='target', edge_weight_column='weight', ...)`
>
> ...
>
> `source_column` (`str`, optional) – The name of the column to use as the source node of edges in the `edges` edge list argument.
> `target_column` (`str`, optional) – The name of the column to use as the target node of edges in the `edges` edge list argument.
> `edge_weight_column` (str, optional) – The name of the column in each of the `edges` DataFrames to use as the weight of edges. If the column does not exist in any of them, it is defaulted to 1.

**Comment by huonw** [comment]
The two solutions have been posted, and it's been 3 weeks since the last comment (and months since the issue was filed), so I'm closing this. Please feel free to comment or open a new issue if things aren't clear or you need further help! Thanks for filing.
