### ISSUE TITLE
How to predict single variable with multivariate input with GCN-LSTM? How about multiple lag timesteps? 

### ISSUE THREAD

**Issue by PanZiwei** [stellargraph/stellargraph#1829]
Hi,
In #1618/#1580  you mentioned that Stellargraph supports multivariate time series to GCN-LSTM and will have a demo soon. My question is:

1. When do you plan to release the demo for the multivariate time series input such as the Urban Air dataset in #1618 ?

2. Is it possible to predict a single variable with multivariate input with GCN-LSTM?

For example, e.g. If my dataset is a multivariate time series of observations including weather temperature, humidity, pm2.5, and other weather-relevant from different weather stations at hour level, and we are only interested in the weather temperature prediction. For a specific station(a node I think), is it possible to use GCN-LSTM to predict 1 output variable(e.g. weather temperature at the current hour) using multiple input variables(input series)? The input variables should have correlations with each other.

I think my question is relevant to #1630. 

3. Is it possible to train the model on multivariate time series forecasting with multiple lag inputs?

Thank you so much for your help!

**Comment by huonw** [comment]
Thanks for waiting for a reply.

> When do you plan to release the demo for the multivariate time series input such as the Urban Air dataset in #1618 ?

Unfortunately there's no immediate plan for this.

> Is it possible to predict a single variable with multivariate input with GCN-LSTM?

Unfortunately not directly, as you are correct that it is #1630. One option would be to predict all of them but only pay attention to the temperature in the loss function and prediction code, so the other outputs are unconstrained/ignored.

> Is it possible to train the model on multivariate time series forecasting with multiple lag inputs?

Do you mean have input of both 10 minutes ago, and 1 hour ago? I think typically this is assumed to be incorporated into the memory of the time series model, like LSTM. That is, one would only feed in the most recent data (smallest lag) and let the model translate this into its internal "knowledge". I may be misunderstanding you. Please let me know.
