### ISSUE TITLE
Write the test() functions with model/transform re-loading

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#185]
### Description
The updated `demos/node-classification/epgm-example.py` and `demos/node-classification/epgm-yelp-example.py` have no test() implemented - it should load the saved model/transforms from disk, and apply them to the graph. These should be written, to show users how to load and apply saved models.

### Done Checklist (Development)
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by huonw** [comment]
With https://github.com/stellargraph/stellargraph/pull/889, we no longer have any of the above scripts, so moving this to done.
