### ISSUE TITLE
AttributeError: 'Attri2Vec' object has no attribute 'in_out_tensors'

### ISSUE THREAD

**Issue by ohjunehun** [stellargraph/stellargraph#1857]
Hello there, was trying the example on Attri2Vec: DBPL Graph however, I encountered this error message?
# Build the model and expose input and output sockets of attri2vec, for node pair inputs:
x_inp, x_out = attri2vec.in_out_tensors()

Thank you for your help.

**Comment by huonw** [comment]
Hi, thanks for filing an issue. Unfortunately I need more information to be able to help you. For example, what version of StellarGraph are you using? The `in_out_tensors` method was added to `Attri2Vec` in version 0.11.0 (the library is now up to version 1.2.1).

**Comment by ohjunehun** [comment]
Hi there, I have tried to update StellarGraph to the latest version and it works, thank you so much :)

**Comment by huonw** [comment]
Great! 👍
