### ISSUE TITLE
How to get link prediction node?

### ISSUE THREAD

**Issue by ohjunehun** [stellargraph/stellargraph#1878]
Hi there,

I am fairly new to machine learning and trained a GraphSAGE Link Prediction model using Stellargraph.

I would like to use the model to predict possible nodes that links to query node, can I use model.predict() for that?

How do I go about getting the predictions for a particular node?

Thank you so much in advance!

**Comment by huonw** [comment]
Yeah, `model.predict` allows you to do this. You have to set up queries of interest and pass them through the `GraphSAGELinkGenerator`. For instance, if you have a single node of interest `query_node` and (relatively) small number of other nodes, and, you could predict `query_node ` against every other node in the graph, something like (untested code):

```python
generator = GraphSAGELinkGenerator(...)

# ...

queries = [(query_node, other_node) for other_node in graph.nodes]
predictions = model.predict(generator.flow(queries))
```

The `queries` list effectively defines the possible links for `query_node`, and the `predictions` array then contains a score for each of them (in corresponding order).

Does that help?

**Comment by ohjunehun** [comment]
Thank you so much, it works!
