### ISSUE TITLE
For the constructed StellarGraph, is there a function similar to add_node/add_edge? 

### ISSUE THREAD

**Issue by ghost** [stellargraph/stellargraph#1890]
import networkx as nx
G = nx.Graph()

G.add_node(1)
G.add_nodes_from([2, 3])

G.add_edge(1,2)
G.add_edges_from([(1, 2), (1, 3)])

**Comment by illcat** [comment]
How to add new nodes during testing? 
ex. StellarGraph.add_node(new_node, features=[2, 3, 4, 5])'

**Comment by huonw** [comment]
Hi @illcat, unfortunately a `StellarGraph` cannot be mutated, so there's no `add_node`/`add_edge` functionality available. What's your broader purpose with wanting these functions?
