### ISSUE TITLE
Demo notebook requires version 1.3.0b

### ISSUE THREAD

**Issue by kmichael08** [stellargraph/stellargraph#1892]
### Describe the bug

I run one of the notebooks -- `graphsage-unsupervised-sampler-embeddings.ipynb`. It says the required version is 1.3.0b and asks to pip install it. However the latest version I can see either on PyPi/Anaconda or releases on your repo is 1.2.1.
Am I missing something?

**Comment by huonw** [comment]
Hi, thanks for filing a bug. The 1.3.0b version refers to the current state of the default `develop` branch. You can find the versions specific to a given version in two ways:

- in the online docs: https://stellargraph.readthedocs.io/en/stable/demos/index.html (each notebook includes a download link)
- under the `master` branch (for the latest version) or the corresponding git tag (e.g. `v1.2.1` for 1.2.1): `git checkout master` or `git checkout v1.2.1` and the finding them in the file path

Does that make sense?

**Comment by kmichael08** [comment]
Makes sense, thanks!
