### ISSUE TITLE
Tensor input error in the GCN-LSTM model

### ISSUE THREAD

**Issue by grand-home-projects** [stellargraph/stellargraph#1893]
Hello, 

I was just trying to walk through the demo/example for the GCN-LSTM model on my machine (running Ubuntu 20.04/Python 3.8), and ran into an error when executing the "model.fit" portion:

> ValueError: Layer model_4 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 207, 100) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 207) dtype=float32>]

Knowing that there was also a google colab version of this, I went to double check the notebook as my first level of troubleshooting to confirm that the code ran successfully on your end too. However, when I ran it on your linked colab notebook, I got the same error that I got when on my machine:

>ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1233 test_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1224 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1217 run_step  **
        outputs = model.test_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1183 test_step
        y_pred = self(x, training=False)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/input_spec.py:207 assert_input_compatibility
        ' input tensors. Inputs received: ' + str(inputs))

    ValueError: Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 207, 10) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 207) dtype=float32>]

This makes me suspect that an update somewhere broke the underlying gcn_lstm function's ability to pass inputs/outputs properly. Definitely would appreciate any help to figure this out. Thanks!

**Comment by huonw** [comment]
Hi @grand-home-projects, this is unfortunately an issue where TensorFlow 2.4 slightly changed behaviour of the `fit` function, so that `model.fit(..., validation_data=[x, y])` is, I think, feeding in two input tensors, rather than inputs `x` and labels `y`. It's fixed on the `develop` branch (in https://github.com/stellargraph/stellargraph/pull/1840), but not yet released. You can fix manually by changing the list to a tuple:

```python
history = model.fit(
    trainX,
    trainY,
    epochs=100,
    batch_size=60,
    shuffle=True,
    verbose=0,
    validation_data=(testX, testY), # changed from [testX, testY]
)
```

Does that make sense?

**Comment by grand-home-projects** [comment]
Yes, that worked perfectly. Thank you!
