### ISSUE TITLE
How to provide multiple head node types to HinSAGELinkGenerator? 

### ISSUE THREAD

**Issue by UCRajkumar** [stellargraph/stellargraph#1908]
I have a multi-partite heterogeneous graph with 4 node types. I am trying to do something like this demo: https://stellargraph.readthedocs.io/en/stable/demos/embeddings/graphsage-unsupervised-sampler-embeddings.html

However, I'm trying to do it with HinSage. One issue I'm having is when using the `HinSAGELinkGenerator()` function, the `head_node_types` argument only accepts a pair. But I have four node types. 

How can I get around this issue?

My final goal is just to be able to produce meaningful node embeddings for new graphs in the future with the same node and edge types so I'm not necessarily bent on using LinkGenerator/NodeGenerator.

**Comment by adocherty** [comment]
Hi,

Thanks or the question.  The `HinSAGELinkGenerator` generates pairs of nodes with a specified type pattern and does not currently support multiple link types.  Note that with four nodes you will have 6 different potential edge types.

If you are interested in unsupervised embeddings of a heterogenous graph, you could try the ComplEx knowledge graph algorithm, and example is here: https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/complex-link-prediction.html

However, as your graph is multi-partite you may have problems with embeddings not being consistent between parts, in this case you could try using Deep Graph Infomax, where you can still use your HinSAGE model with DGI training as described in this example: https://stellargraph.readthedocs.io/en/stable/demos/embeddings/deep-graph-infomax-embeddings.html

I hope this helps.

**Comment by UCRajkumar** [comment]
This is really helpful to know, thank you. I will test it out those methods.

**Comment by howDareYouSayThat** [comment]
> you may have problems with embeddings not being consistent between parts

Hi, thanks for your help. May I ask if these two links are also could be useful in link prediction task on a heterogeneous graph (multi-type nodes and edges).
