### ISSUE TITLE
Unable to extract base model from trained deep graph infomax model

### ISSUE THREAD

**Issue by UCRajkumar** [stellargraph/stellargraph#1912]
I've trained a deep graph infomax model with graphsage as it's base model. I only saved the deep graph infomax model. Is there a way to extract the trained graphsage model from within the trained DGI model or do i need to have saved the original graphsage model as well?

I'm trying to repeat this portion of the demo:

```
x_emb_in, x_emb_out = gcn_model.in_out_tensors()

# for full batch models, squeeze out the batch dim (which is 1)
x_out = tf.squeeze(x_emb_out, axis=0)
emb_model = Model(inputs=x_emb_in, outputs=x_out)
train_subjects, test_subjects = model_selection.train_test_split(
    node_subjects, train_size=0.1, test_size=None, stratify=node_subjects
)

test_gen = fullbatch_generator.flow(test_subjects.index)
train_gen = fullbatch_generator.flow(train_subjects.index)

test_embeddings = emb_model.predict(test_gen)
train_embeddings = emb_model.predict(train_gen)

lr = LogisticRegression(multi_class="auto", solver="lbfgs")
lr.fit(train_embeddings, train_subjects)

y_pred = lr.predict(test_embeddings)
gcn_acc = (y_pred == test_subjects).mean()
print(f"Test classification accuracy: {gcn_acc}")
```
Instead of GCN, I'm doing it with graphsage.

**Comment by huonw** [comment]
Hi, thanks for filing an issue!

I think it will be much easier if you save the original GraphSAGE model, but I think you can probably try and pull out the specific input and output layers too. You probably only need to save the Deep Graph Infomax model if you wish to further train or fine-tune it. If you just want to use the trained GraphSAGE model, only save that one.

For manually pulling out the layers, In the current implementation, the normal input layers are after the "corrupted" inputs, and the output layer will be buried somewhere within the model. You may have to manually inspect `model.layers` to find the last of the GraphSAGE layers, which I think will be a `Lambda` layer. I haven't tested this, but it might look something like:

```python
# load DGI model
loaded_dgi = tf.keras.models.load_model("...")

# find the layers for the basic GraphSAGE model with the DGI model
graphsage_inputs = loaded_dgi.inputs[len(loaded_dgi.inputs) // 2:]
graphsage_output = loaded_dgi.layers[123] # you'll need to find this yourself, as it will depend on your GraphSAGE config
loaded_graphsage = tf.keras.Model(inputs=graphsage_inputs, outputs=graphsage_output)

# use the GraphSAGE model normally
generator = GraphSAGENodeGenerator(...)

loaded_graphsage.predict(generator.flow(...))
```

I haven't tested this, so it may not work without further edits. If you try it out and it doesn't work, I'll be able to help better if you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) showing where you get stuck.

**Comment by UCRajkumar** [comment]
This is very helpful, thank you.
