### ISSUE TITLE
neo4j begin(autocommit=True) error

### ISSUE THREAD

**Issue by Kashmira-ms** [stellargraph/stellargraph#1925]
### Describe the bug

*A clear and concise description of what the bug is.*

### To Reproduce

1. *Go to '...'*
2. *Execute '...'*
3. *See error*

### Observed behavior

*Describe or paste the exact output that demonstrates the bug (for example, the stack trace if it is an exception).*

### Expected behavior

*A clear and concise description of what you expected to happen.*

### Environment

Operating system: *for example: macOS, Ubuntu*

Python version: *for example: 3.7.2*

Package versions: *for example: stellargraph==0.8.3, tensorflow==2.0.0*

*The following Python code can automatically compute the data for this section (for example: run the code in a Jupyter notebook cell, or, on macOS, copy the code and run `pbpaste | python -` in a terminal):*
~~~
import subprocess, platform, sys
pkgs = subprocess.Popen(["pip", "freeze"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0].decode("utf-8")
print("Operating system: `{}`\nPython version:\n```\n{}\n```\nPackage versions:\n<details>\n\n```\n{}\n```\n\n</details>".format(platform.platform(), sys.version, pkgs))
~~~

### Additional context

Add any other context about the problem here. For example:

Data used: *if this occurs with a specific dataset, which dataset and how to acquire it*

Screenshots: *if applicable, add some screenshots to explain the behaviour*

**Comment by Kashmira-ms** [comment]
I 'm having the issue while loading cora dataset into neo4j 


TypeError                                 Traceback (most recent call last)
<ipython-input-66-64264485cd67> in <module>()
     14     batch_end = batch_start + batch_len
     15     records = node_list.iloc[batch_start:batch_end].to_dict("records")
---> 16     tx = graph.begin(autocommit=True)
     17     tx.evaluate(loading_node_query, parameters={"node_list": records})

TypeError: begin() got an unexpected keyword argument 'autocommit'

**Comment by jeffypie369** [comment]
Hello Kashmira-ms,

In case you have not resolved your issue, the 'autocommit' argument in begin() has been removed by py2neo in their latest versions. You may refer to https://py2neo.org/2021.1/workflow.html#py2neo.Graph. 
![image](https://user-images.githubusercontent.com/39295219/120660768-3d84b300-c4ba-11eb-94c1-74526cb65359.png)

Instead, simply use graph.auto().

Hope this helps. Cheers!
