### ISSUE TITLE
AttributeError: module 'py2neo' has no attribute 'cypher_escape'

### ISSUE THREAD

**Issue by jeffypie369** [stellargraph/stellargraph#1931]
Receive the titled error when attempting to run the following line from the directed GraphSAGE demo:

    neo4j_sg = Neo4jStellarDiGraph(neo4j_graphdb, node_label="paper")

The issue is that in stellargraph/connector/neo4j/graph.py, the method raw_and_cypher calls py2neo.cypher_escape(raw). This is perhaps outdated as the py2neo docs have cypher_escape() under py2neo.cypher.

This bug is fixed if line 105

    return raw, py2neo.cypher_escape(raw)

is replaced with

    return raw, py2neo.cypher.cypher_escape(raw)

**Comment by Kashmira-ms** [comment]
**I'm still facing this issue after replacing line 105. Is there any suggestion**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-e46b81ea1339> in <module>()
----> 1 neo4j_sg = Neo4jStellarGraph(neo4j_graphdb, node_label="paper")
      2 neo4j_sg.cache_all_nodes_in_memory()

2 frames
/usr/local/lib/python3.7/dist-packages/stellargraph/connector/neo4j/graph.py in raw_and_cypher(raw)
    103         def raw_and_cypher(raw):
    104             if raw is not None:
--> 105                 return raw, py2neo.cypher.cypher_escape(raw)
    106             else:
    107                 return None, None

AttributeError: module 'py2neo' has no attribute 'cypher_escape'
