### ISSUE TITLE
ResourceExhaustedError training graph with 112950391 edges and 13553925 nodes (10 different relation types) in system 430GB RAM and 8XNVIDIA® V100 GPU

### ISSUE THREAD

**Issue by tekrajchhetri** [stellargraph/stellargraph#1989]
Hi all,

I am training RGCN on a graph with 112950391 edges and 13553925 nodes. The graph has 10 different relationship types. But I am getting ResourceExhaustedError.

Computing resources:

- RAM: 430 GB
- GPU:  8XNVIDIA® V100 GPU
- CPU: 92 Core

I have 6 RGCN layers (32,64,128 (x2) and 154 (x2)) and epoch size of 500.  Any help?

**Comment by iknoorjobs** [comment]
Hi @tekrajchhetri 
I am also getting ResourceExhaustedError error, even though both RAM and GPU are available. Could you please tell if there are any workarounds to fix this? The graphs in my training set are quite large (~250+ nodes).
Thanks
