### ISSUE TITLE
get_node_importance for Graph Classification?

### ISSUE THREAD

**Issue by aelhossiny** [stellargraph/stellargraph#1997]
Thank you for the wonderful tool! I have a question, can I use `get_node_importance` function in graph classification model? I found it implemented on predicting[ node classification on CORA network](https://stellargraph.readthedocs.io/en/stable/demos/interpretability/gcn-node-link-importance.html), but I have a graph classification project using the [DGCNN pipeline](https://stellargraph.readthedocs.io/en/stable/demos/graph-classification/dgcnn-graph-classification.html) and I hope to have a saliency map for the nodes attributed to specific class?

Thanks

**Comment by rupjit-bo** [comment]
I am looking for something similar. Have you found any solution for this @aelhossiny

**Comment by aelhossiny** [comment]
@rupjit-bo I found this paper, but it's using pytorch geometric implementation.

**Comment by rupjit-bo** [comment]
@aelhossiny Please point me to the paper

**Comment by aelhossiny** [comment]
Sorry, I thought that I sent it. Here it is (https://arxiv.org/abs/1903.03894)

**Comment by rupjit-bo** [comment]
Thank you.

**Comment by mmpust** [comment]
Hey Ahmed, did you find a stellargraph-specific solution?

**Comment by aelhossiny** [comment]
Unfortunately not
