### ISSUE TITLE
Getting Unicode decode error while loading Movielens data

### ISSUE THREAD

**Issue by meg261995** [stellargraph/stellargraph#2058]
HI,

I am trying to reproduce 'Link prediction with Heterogeneous GraphSAGE (HinSAGE)' example code with MovieLens dataset. 
Getting unicode decode error while loading the dataset

from stellargraph import datasets
dataset = datasets.MovieLens()
dataset.load()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 76620: invalid continuation byte.

**Comment by MeghanaSreenath** [comment]
Update: Solved it by giving proper encoding value in load() method of MovieLens class in datasets.py present in .../stellargraph/datasets/datasets.py

**Comment by meg261995** [comment]
Update: Solved it by giving proper encoding value in read_csv of MovieLens.load() in datasets.py. Location:/stellargraph/datasets/datasets.py

Hope this helps others :)

**Comment by Gabriel-1023** [comment]
add encoding='latin-1' at line 424
Location:/stellargraph/datasets/datasets.py
