### ISSUE TITLE
Trouble installing Stellargraph in Google Colab

### ISSUE THREAD

**Issue by michalis-alex** [stellargraph/stellargraph#2082]
### Describe the bug

I had previously installed and used stellargraph multiple times in Google colab up until a few days ago without any issues. However, for some reason the distribution cannot be found anymore when I am trying to install it. Did anybody else come across the same issue?

### To Reproduce

1. *Go to Google Colab*
2. *Execute '!pip install stellargraph'*
3. *See error below*

### Observed behavior

*Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement stellargraph (from versions: none)
ERROR: No matching distribution found for stellargraph
*

### Expected behavior

*I was expecting stellargraph to install properly.*

### Environment

Python version: *3.9.16*

**Comment by cloudmadeofcandy** [comment]
Sir you did not just closed this without giving us further information??????

**Comment by michalis-alex** [comment]
I am sorry for that, I realized that there was nothing we can do about it since stellargraph requires an older Python version and it's very difficult to change the Python version in Google Colab . So unless they update the stellargraph libraby, what I am suggesting is to install it to your local computer with a virtual environment.

**Comment by iamanimesh11** [comment]
are you still active 
let me know if there is solution you got

**Comment by cloudmadeofcandy** [comment]
> are you still active let me know if there is solution you got

While I am still active, I afraid that our research team had abandoned the framework. We split the team into 2, one team implemented from scratch and one migrated all logic to PyTorch Geometric. While team 1 achieved good results, team 2 completed the migration significantly quicker. Hence PyTorch Geometric is adopted into our system.
