### ISSUE TITLE
Colab Python Version Issue : Stellar graph version not support to the current python version on colab

### ISSUE THREAD

**Issue by VenkateshwaranB** [stellargraph/stellargraph#2084]
### Discussed in https://github.com/stellargraph/stellargraph/discussions/2083

<div type='discussions-op-text'>

<sup>Originally posted by **VenkateshwaranB** March 27, 2023</sup>
In google CoLab, the python current version is 3.10 something, but the stellar graph library only supports python version 3.6.0. I tried to change the version but I facing too many new issues with this. So please provide a solution for that. 

Please refer to the image.

![colab error](https://user-images.githubusercontent.com/48711041/228021705-3fb2fb9f-6a16-4d8a-bd4c-03545659735a.png)

Thanks 
Venkat</div>

**Comment by sclipman** [comment]
I am having this issue has well. Colab is using Python 3.9.16; however, the latest version of StellarGraph (1.2.1) requires Python >=3.6.0 and <3.9.0.

**Comment by VenkateshwaranB** [comment]
Thanks for your answer, Sir. 

Actually, Sir, I tried to update the python version to 3.6.0 on Colab. but other libraries' dependencies could not meet the actual requirements (I meant the other libraries require python current version). What can I do?

**Comment by sclipman** [comment]
@VenkateshwaranB, I am not the developer nor am I providing an answer. I am simply having the same issue as you.

**Comment by VenkateshwaranB** [comment]
Ok, Prof. Thanks

**Comment by LizaPiya** [comment]
Hey did you get any solution? Facing the same issue for few days.

**Comment by VenkateshwaranB** [comment]
Nope, But I think to obtain the library source codes which means what demo algorithm I want (ex: GCN) and their source codes. I try to root cast what function is involved to operate the algorithm regarding dependencies and class (start to end). Then It will be copied and settled in an orderly manner then I run this library call as just a function call on CoLab. I will try If it works I will update you.

Thanks
Venkat

**Comment by Gabriel-1023** [comment]
run:
`!sudo update-alternatives --config python3`

Then select the python with verion 3.8, input its number and press "enter"

run the followings to check python version and install pip:

`!python3 --version`
`!sudo apt install python3-pip`

Then stellargraph can be installed. But there are still some problems... When I run `import stellargraph as sg`, it says:

`ModuleNotFoundError: No module named 'stellargraph'`...

**Comment by VenkateshwaranB** [comment]
Actually, I got two solutions for that. But I am facing new problem when dealing with keras model (during the model.fit function) like "Value error in user code". 

First solution: 

```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
```
check python version 
```
!python --version
```
ans:   Python 3.8.16

Second Solution :
    I modified the Python version range in the setup.py for the stellargraph library 

```
line no : 97   python_requires=">=3.6.0, <3.10.0",
```
you can use this like
```
!pip install git+https://github.com/VenkateshwaranB/stellargraph.git
```

In both scenario I am facing the Value error in user code issue. (refer to the screenshot below).
![issue](https://user-images.githubusercontent.com/48711041/232703503-7cbfd59a-65ce-4f21-bb33-6ff8171e584c.png)


I will try to sort out this problem soon!!!

**Comment by Gabriel-1023** [comment]
Thanks!!

**Comment by VenkateshwaranB** [comment]
Hello Everyone,
     Finally, I fixed the entire problem, you can use the following procedure to get the stellargraph library on CoLab

First, the stellargraph library supports the TensorFlow 2.11.0 (from my research). So install it.
```
!pip install tensorflow==2.11.0
```
Second, the modified python version library only available on the my forked repo. so use this like
```
!pip install git+https://github.com/VenkateshwaranB/stellargraph.git
```
Finally you use whatever you want!!!

Thanks
**Venkat**

**Comment by Gurjotsingh2002** [comment]
It is giving import error from last 2 days any idea why?
ModuleNotFoundError: No module named 'stellargraph'

**Comment by Gabriel-1023** [comment]
Maybe you can restart your Colab machine and use the following command (Python version from Colab just upgraded, which make the stellargraph from [VenkateshwaranB](https://github.com/VenkateshwaranB) unavailable, I updated the code by directly canceled it's version restriction)
`!pip install git+https://github.com/Gabriel-1023/stellargraph`

**Comment by VenkateshwaranB** [comment]
Good solution @Gabriel-1023. I also modified it.

```
!pip install git+https://github.com/VenkateshwaranB/stellargraph.git
```

**Comment by Gurjotsingh2002** [comment]
Thanks for solution. It is working fine now

**Comment by jsonnermit** [comment]
I had these same troubles, but I found that installing an earlier version of python in colab works. I faced a similar problem where there was "no module named 'disutils.cmd' if you face this too, I recommend doing it works great! 
![Screenshot 2023-11-22 at 3 29 05 PM](https://github.com/stellargraph/stellargraph/assets/110893647/722c06df-5b5f-418d-8651-254a2da48655)
![Screenshot 2023-11-22 at 3 29 38 PM](https://github.com/stellargraph/stellargraph/assets/110893647/83c04986-731c-4290-8455-c7ec5b5981d2)

**Comment by deliamoreno2295** [comment]
Thanks!! You're the best!

**Comment by pansakk** [comment]
@VenkateshwaranB Did you solve the "(during the model.fit function) like "Value error in user code"."? Because I am facing the exact same error on my machine. Same code in friends machine runs ok.

**Comment by VenkateshwaranB** [comment]
Hi @pansakk, Thanks for asking.

Can you please explain a bit? Where exactly did the error occur (line no., function) or something?

**Comment by shreyakiyoor** [comment]
@VenkateshwaranB many thanks for the workaround.

To add on to the available information, I was facing "**Module not found distutils**" after **pip install git+https://github.com/VenkateshwaranB/stellargraph.git** while running on a virtual environment in vscode.

However doing a **pip install setuptools** helped me on this front https://stackoverflow.com/questions/77931666/modulenotfounderror-no-module-named-distutils-how-to-solve-this-in-macos
