### ISSUE TITLE
Pip install PyPi procedure

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#224]
### Description
We need to add the Pip install PyPi procedure and be very clear on how the demos are to be installed.

### Done Checklist (Development)
- [x] Code on PyPi
- [x] Documentation clearly outlining PyPi procedure including demos + tests

**Comment by youph** [comment]
@adocherty is this issue Done?

**Comment by adocherty** [comment]
The procedure is written in this document:
https://docs.google.com/document/d/1oSSzf66c-NoADUfMkFFEeUzhTiFGxoxg287J_M5K7p4/edit
