### ISSUE TITLE
Networkx Deprecation warning

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#233]
### Description

Networkx v2.1 produces the following deprecation warning,

/Users/******/anaconda3/envs/stellargraph/lib/python3.5/site-packages/networkx/algorithms/components/connected.py:86: DeprecationWarning: connected_component_subgraphs is deprecated and will be removedin 2.2. Use (G.subgraph(c).copy() for c in connected_components(G))
  _warnings.warn(msg, DeprecationWarning)

We should update to make sure that this does not cause problems when networkx v2.2 is released.

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request
- [x] Unit tests updated if necessary
- [x] Code well commented

**Comment by youph** [comment]
Please update with the Done Checklist
