### ISSUE TITLE
Node2vec for weighted graphs

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#241]
### Description

Our current implementation of biased random walks used for the node2vec algorithm assume that the graph is unweighted. In other words, transition probabilities do not take edge weights into account assuming that all edges have weight 1.0. The original node2vec paper allows for edge weights. 

We should extend our biased random walker to take edge weights into account.

### User Story
As a: Research Engineer and Data Scientist
I want: to apply the node2vec representation learning algorithm on weighted graphs
so that: I can tackle a larger range of graph problems.

### Done Checklist (Development)
- [x] Produced code for required functionality
- [ ] Units tests
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Relevant docstrings are updated

**Comment by youph** [comment]
@PantelisElinas should it be a modification to the Biased Random Walker class (which would look for link weights, or use default weights of 1 if no weights are specified), or a new class?

**Comment by PantelisElinas** [comment]
Hi @youph and @habiba-h 

I don't think we need a new walker for this. We should probably just add a flag, parameter to the run() method, to the existing one as to whether it should use edge weights or not. The default should be "False" so that current functionality and tests are not effected. Specifying "False" would automatically assume edges have weight 1 so the code doesn't need to be changed.

In the implementation, we should make sure not to check the value of the above flag for every edge we calculate the transition probability for 'cause such a check might increase running time (that is already not the best.)

We might have to assume that an edge has a weight property with a known label, e.g., "weight", or else we might want to allow the caller to specify the label name as another parameter with a default value such as "weight".

Regards,

P.
