### ISSUE TITLE
Maintaining/Developing Python library

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#242]
### Description

This epic captures the following tasks/activities related to maintaining the `StellarGraph` python library:  
- Backlog cleanup  
- Bug fixes  
- External pull requests  
- CLA maintenance

Tasks related to developing the library:  
- API changes  
- Abstracting away NetworkX  
- Pandas support  
- Data preparation (graph-specific)  
- Model deployment  
- etc.

### Done checklist  
- [ ] Issues in this epic are acted upon within a reasonable time  
- [ ] No or few unresolved issues remaining in this epic by the end of v0.3 release

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://csiro.aha.io/features/SGML-8

**Comment by timpitman** [comment]
closing this long-running Epic as we change management of the library - to be replaced by more specific (and not ongoing) Epics in future.
