### ISSUE TITLE
Bitcoin use case

### ISSUE THREAD

**Issue by annitrolla** [stellargraph/stellargraph#257]
### Description
Using data about bitcoin transactions and a list of confirmed ransomware cases we want to apply node classification techniques using `stellargraph` in order to demonstrate the capabilities of the techniques and the library. 

### Done Checklist
- [ ] Completed analysis of the provided data (on a small subset and on the whole 500 mln nodes)
- [ ] A jupyter notebook with the story 
- [ ] Feedback to the ml team how to extend to the library
- [ ] Team demo

**Comment by youph** [comment]
Issue moved to [stellargraph/stellargraph-ml-private-issues #8](https://github.com/stellargraph/stellargraph-ml-private-issues/issues/8) via [**ZenHub**](https://www.zenhub.com/)
