### ISSUE TITLE
Test coverage for StellarGraph library

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#258]
### Description
We need to measure test coverage, and prohibit PR merge if it reduces the overall test coverage.
Possible candidates for measuring test coverage:
- codecov.io
- pycov

### Done Checklist (Development)
- [x] Test coverage
- [x] test coverage badge in the repo
- [x] Buildkite rule to block PRs that reduce the overall test coverage

**Comment by TheDen** [comment]
@youph I've got tests working with `pytest-cov` and I'm using coveralls.io (it's free for open source repos)

I'll set up a PR we can try today, that will check off 1 and 2 in the checklist.

For 3, we can have status APIs that will show coverage and fail if it doesn't meet a threshold or gets reduced by a percentage

![image.png](https://images.zenhubusercontent.com/5b189e3ab709d021406865ae/9afae465-b88c-40bf-8cfb-52b9f1fb8083)

**Comment by youph** [comment]
@TheDen thanks, that's great!
