### ISSUE TITLE
Policy networks

### ISSUE THREAD

**Issue by annitrolla** [stellargraph/stellargraph#259]
### Description
One of the researchers provided two (small) datasets of policy networks. The idea is to evaluate whether these datasets can be used for `stellargraph` library

### Done Checklist
- [ ] Descriptive analysis of the datasets to evaluate whether they are useful for any of the ml tasks
- [ ] Decision whether to continue with the collaboration

**Comment by arc0** [comment]
Issue moved to [stellargraph/stellargraph-ml-private-issues #1](https://github.com/stellargraph/stellargraph-ml-private-issues/issues/1) via [**ZenHub**](https://www.zenhub.com/)
