### ISSUE TITLE
To implement the basic graph ER

### ISSUE THREAD

**Issue by wangzhen263** [stellargraph/stellargraph#260]
### Description
This task is to re-implement graph ER in python code which includes blocking for candidates selection, graphSAGE for link prediction, and plotting figures. This work will be used for the graph ER research in the next step.

The implementation should include:
- [x] GraphSAGE feature-based graph ER
- [x] Node2vec feature-based graph ER
- [x] Blocking
- [x] Evaluation of the performance of each method

### Done Checklist (Development)
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo
- [x] Team demo/review

**Comment by youph** [comment]
@wangzhen263 hey Jeff, is this currently In Progress?

**Comment by wangzhen263** [comment]
yes, just moved it to progress

**Comment by youph** [comment]
Code repo: https://github.com/stellargraph/pyGraphER

**Comment by wangzhen263** [comment]
So will we close this?

**Comment by youph** [comment]
@wangzhen263 we still need to review the code, as discussed. Could you please create a PR and assign @adocherty and myself as reviewers?
