### ISSUE TITLE
Implement the embedding Interpretation method

### ISSUE THREAD

**Issue by sktzwhj** [stellargraph/stellargraph#266]
Description
Implement the algorithm described in the KDD'18 paper to interpret the embeddings. 

Done Checklist (Development)
- [x] Implement the algorithms for global/local interpretations. 
- [x] Experiment on node2vec embeddings of CORA dataset.

Reference
Ninghao Liu, Xiao Huang, Jundong Li, Xia Hu. On Interpretation of Network Embedding via Taxonomy Induction. Proceedings of the 24th ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD'18). [link](http://delivery.acm.org/10.1145/3230000/3220001/p1812-liu.pdf?ip=130.155.160.187&id=3220001&acc=ACTIVE%20SERVICE&key=65D80644F295BC0D%2ED2AA393F9B7AEC6D%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1541131795_8905e5fda426b7d124967b4ef2e1180f)

**Comment by youph** [comment]
@sktzwhj could you please: 
- Give an Estimate for this task
- Add a link to the KDD paper you're referring to

**Comment by youph** [comment]
@sktzwhj shouldn't this be moved to In Progress?

**Comment by youph** [comment]
@sktzwhj: cora embeddings (d=16) obtained from GCN with node classifier on top:
[cora.emb.zip](https://github.com/stellargraph/stellargraph/files/2508578/cora.emb.zip)

**Comment by sktzwhj** [comment]
@youph Thanks! Issue moved to In Progress.

**Comment by youph** [comment]
The code that generated the embeddings is here:
https://github.com/NICTA/gcn
`./gcn/train.py`

**Comment by sktzwhj** [comment]
@youph Is that a private repo? Seems I don't have access to that.

**Comment by youph** [comment]
I've added you as a collaborator

**Comment by youph** [comment]
Is this Done?

**Comment by sktzwhj** [comment]
Yes. The code has been merged. I will close this issue.
