### ISSUE TITLE
Setup CLA bot for stellargraph

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#269]
### Description

We need to make it much easier to contribute to the library. We need a CLA, and to make this easier than an emailed signature, we can setup a bot to make a one-click path.

### Done Checklist (Development)

- [x] Working CLA bot for signing  

- [ ] David Lau to approve  

- [x] Tested with extra user

Aha! Link: https://csiro.aha.io/features/SGML-7

**Comment by youph** [comment]
@arc0 is there a CLA template from another data61 team that we can use?

**Comment by TheDen** [comment]
@youph what do you think of cla-assistant?
https://cla-assistant.io/
https://github.com/cla-assistant/cla-assistant

It's free and looks pretty easy to set up, we just need to make a GitHub Gist file with our CLA and the bot manages what we need.

I can set it up on one of my personal public repos for us to try it out. Of course we still need a CLA for `stellargraph` before we can deploy it.

**Comment by youph** [comment]
@arc0 can we get the CLA for `stellargraph` from legal?

**Comment by youph** [comment]
@TheDen the CLA assistant looks great and easy to use. @arc0 asked someone from the legal team for a CLA that's been floating about data61, hopefully we get it soon.

**Comment by TheDen** [comment]
@youph I've tested it on one of my personal repos—here's a PR with the CLA signed https://github.com/TheDen/0xfee1dead.top/pull/5

It works really well! You can give it a try, just make a PR and see how it goes 👍

**Comment by youph** [comment]
Nice! @arc0 are there any updates from the legal guy on CLA?

**Comment by arc0** [comment]
Our CLA is sent to legal

**Comment by TheDen** [comment]
Tested with a PR from an external user https://github.com/stellargraph/stellargraph/pull/293
