### ISSUE TITLE
Create a forum for stellargraph

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#296]
### Description
We are getting questions about the Stellargraph library via emails, linkedin, etc. It would be good to create a forum for all the discussions, in addition to github issues.

@TheDen do you know any forum platforms that are free and easy to use? Previous discussions suggested the following options so far:
- [Discourse](https://www.discourse.org/)
- [Gitter](https://gitter.im/)

### Done Checklist (Development)
- [ ] Forum platform chosen
- [ ] Forum created
- [ ] Team demo of how to use the forum

**Comment by TheDen** [comment]
@youph I've creatde a gitter.im for StellarGraph https://gitter.im/StellarGraph so we can give that a try.

However it seems to be more like an IRC channel or Slack rather than a traditional forum. Upside is that it's free. Discourse is good, but pricey ($100/mo for standard)

**Comment by TheDen** [comment]
I like Nim https://github.com/nim-lang/nimforum (example https://forum.nim-lang.org/) since it's free, but we'll have to self-host which may not be much of an issue

**Comment by TheDen** [comment]
There's also:

* https://muut.com/ ($16 /mo for mini)
* https://discuss.flarum.org/ (hosted, similar to `nimforum` but still in beta)
* https://esotalk.org/ (predecessor to Flarum)
* https://mybb.com/ (hosted, mature but may need work to make it _mordern_ looking)

**Comment by youph** [comment]
@TheDen thanks for creating gitter community! Do you know if it's possible to have "topics" there similar to Nim? Nim looks good :)

**Comment by TheDen** [comment]
Apparently you can self host discourse for free, hmm https://github.com/discourse/discourse/blob/master/docs/INSTALL.md

Only docker though, so maybe I'll do a trial deployment on k8s
