### ISSUE TITLE
Change StellarGraph class to NOT inherit from networkx.Graph() class

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#297]
### Description
Currently, `StellarGraph` class inherits from `networkx.Graph` class, inheriting all of its methods. While this allows us to use the networkx methods for Stellargraph objects, the problem is that many of these methods (e.g., `.copy()`) produce a `networkx.Graph` object as a result, i.e., applying these methods to `StellarGraph`-typed objects changes the type of the object to `networkx.Graph`, losing the information specific to the original `StellarGraph` object (e.g., node features). 

To avoid this confusing behaviour, we need to make `StellarGraph` a `class StellarGraph(object)`, with constructor taking two arguments: a networkx graph, and an optional pandas dataframe with node attributes. We also need to implement the methods that are used by explorers, etc., e.g., `.nodes()`, `.edges()`, `.neighbours()`, `.copy()`, etc. While this requires extra work to implement, the advantage is that the result of these methods would be of the same type, `StellarGraph`, with all the internal information retained.

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] Documentation in repo
- [ ] Team demo

**Comment by youph** [comment]
@adocherty We've discussed this a while ago, creating an issue to address in this release.

**Comment by youph** [comment]
@adocherty @PantelisElinas this issue has been in the backlog for a while. Let's discuss to see if this is still relevant, and when we should address it.

**Comment by geoffj-d61** [comment]
@youph @adocherty I figured I'd have a look at this as well whilst I'm thinking about the whole StellarGraph class implementation framework (unless anyone has objections). Subsequent integration of the proposed new classes into the system will require me to understand just what functionality is currently used, anyway.

**Comment by geoffj-d61** [comment]
Hi @adocherty , I have a local branch (not yet pushed) that makes StellarGraph and StellarDiGraph pure interfaces (in the Java or C++ concepts), and makes StellarGraphBase (renamed to NetworkXStellarGraph) a functional but hidden implementation. This currently passes all the unit tests, but I have forgotten how to manually run the demo tests. Can you please remind me how?

The redesign is not yet fully complete, as there are still NetworkX calls made by various classes (via a `get_networkx_graph()` implementation method), but it looks very promising and fits nicely in line with my ideas about the new, efficient classes we are designing. Some implicit NetworkX functionality has been made explicit, and this is what might break the demos if they rely upon implicit behaviour (e.g. `len(G)` and `list(G)`, etc.).

**Comment by geoffj-d61** [comment]
@adocherty , I've pushed what code I currently have - still need to work through all the places that call `get_networkx_graph()` and rummage around the graph structure (usually for features and attributes).

**Comment by geoffj-d61** [comment]
Hmm, I've realised I never encountered to `copy()` functionality. I will need to look into this further.
