### ISSUE TITLE
To add GCN to our library

### ISSUE THREAD

**Issue by wangzhen263** [stellargraph/stellargraph#304]
### Description
Graph Convolutional Networks (GCNs) is a recently proposed architecture which has had success in semi-supervised learning on graph-structured data. It is an important member of graph researches. I will port GCN into our stellargraph library.

Dataset will be Cora at this moment.

### Done Checklist
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo

**Comment by youph** [comment]
Check out the keras implementation of GCN by Kipf

**Comment by wangzhen263** [comment]
PR https://github.com/stellargraph/stellargraph/pull/318
