### ISSUE TITLE
Add unsupervised GraphSAGE to the library

### ISSUE THREAD

**Issue by habiba-h** [stellargraph/stellargraph#305]
### User Story
As a: Data Scientist
I want: everything that GraphSAGE offers
so that: I have freedom for my unsupervised method experiments

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo

**Comment by youph** [comment]
@habiba-h have the READMEs been updated to include unsupervised GraphSAGE?
