### ISSUE TITLE
Multiple graph training

### ISSUE THREAD

**Issue by kidtronnix** [stellargraph/stellargraph#319]
First off thanks for this amazing project. Getting some amazing results using it. :+1: 

### Description

So i have many examples of different graphs all of which have the same node features (different values). I would like to use multiple graphs during training so I can train using all the data I have. What is the recommended way to implement this?

### User Story

As a: researcher

I want: to train link prediction embeddings on multiple graphs

so that: model learns generalised embeddings

**Comment by youph** [comment]
@kidtronnix 
There are a couple of options to do what you want:
1. Merge all your graphs into one graph, and train your model on that
2. Train the model on one graph at a time for a few epochs, then continue training on the next graph (without resetting the model weights), etc. 
In terms of simplicity of implementation, I'd recommend the 1st option. Note that, for link prediction task, you need to take care to generate negative training link examples from each of your graphs, rather than from the combined graph, to avoid having inter-graph negative link examples in the training set (assuming your graphs are not connected to each other).

**Comment by kidtronnix** [comment]
@youph thanks for the quick response, so helpful!

Good news I already generate my own negative link examples for each graph. Will give this a go, and let you know if I have any trouble with the stellargraph object conversion but I think I can see how to do it.

:)

**Comment by youph** [comment]
Great, let us know how you go. We’d also love to learn more about your use case for the library.

**Comment by kidtronnix** [comment]
Ok so everything went fine creating a big graph. More data didn't actually help that much, but that's an issue on my side ;).

Unfortunately I can't speak about my use case in too much detail at the moment, but at a high level...

I am using a space-time network as a representation of a "world" and then I am trying to classify edges, to allow me to localize certain properties of said world. My graphs have approximately 50,000 nodes (depending on bucketing width), and I have multiple instances of them.

**Comment by youph** [comment]
I'm glad it worked.
Out of curiosity: how long, per epoch, does it take to train your model on the combined graph (which, I presume, has m*50k nodes, where m is the number of graph instances, and how many edges?), and what computational resources are you using?

**Comment by qillbel** [comment]
Dear @kidtronnix and @youph, I have a similar problem and would like to confirm something. 
When you merge all your graphs, does it mean the generated single graph has multiple disconnected subgraphs in it? 
And if I want to do node classification, what is the best technique you would recommend for this problem?
Thanks in advance.

**Comment by youph** [comment]
> Dear @kidtronnix and @youph, I have a similar problem and would like to confirm something.
> When you merge all your graphs, does it mean the generated single graph has multiple disconnected subgraphs in it?
> And if I want to do node classification, what is the best technique you would recommend for this problem?
> Thanks in advance.

If the graphs being merged are not connected to each other, then yes - the resulting graph would have multiple disconnected subgraphs in it. This would potentially be a problem if you then try to predict links in this combined graph, but shouldn't be a problem for node tasks, e.g., node classification.

As for the best technique for node classification: it's hard to tell in advance which would be best for your data, so I'd recommend trying several and choosing the one that works best. We have a number of node classification algorithms in the library, with demos: https://github.com/stellargraph/stellargraph/blob/develop/demos/node-classification/README.md
