### ISSUE TITLE
StellarGraph info method does not give information on numerical features.

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#333]
**Describe the bug**
When I provide networkx graph and features along with it:

```Gs = sg.StellarGraph(G, node_features=node_features)```

if the graph `G` already has some attributes assigned, will they be used in training or not?

If the node_features are provided and the graph has attributes, `StellarGraph` shows only the graph attributes in the `info` method and for some reason, node features provided directly in the `node_features` argument are not shown in the summary:
```
> Gs.info()

 StellarGraph: Undirected multigraph
 Nodes: 2010, Edges: 2013

 Node types:
  default: [2010]
        Attributes: {'degree', 'star', 'betweenness'}
```

**To Reproduce**
1. Create a NetworkX graph with node attributes.
2. Create a StellarGraph object `Gs` with numerical features provided in the `node_features` argument.
4. Information in `Gs.info()` only shows the original node attributes, and no information on the numerical features is given.

**Expected behavior**
Information on the features actually used for the ML algorithms is shown.

**Comment by gijswobben** [comment]
Any updates on this?

**Comment by huonw** [comment]
Hi @gijswobben, in #979 we added an extra line to give more info, e.g. on the Cora dataset, `info` now looks like:

```
StellarGraph: Undirected multigraph
 Nodes: 2708, Edges: 5429

 Node types:
  paper: [2708]
    Features: float32 vector, length 1433
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5429]
```

And on the MovieLens which has two node types with different feature sizes:

```
StellarGraph: Undirected multigraph
 Nodes: 2625, Edges: 100000

 Node types:
  movie: [1682]
    Features: float32 vector, length 19
    Edge types: movie-rating->user
  user: [943]
    Features: float32 vector, length 24
    Edge types: user-rating->movie

 Edge types:
    user-rating->movie: [100000]
```

(Note the `Features: ...` line.)
