### ISSUE TITLE
UniformRandomMetaPathWalk doesn't update the current node neighbors

### ISSUE THREAD

**Issue by afdezt** [stellargraph/stellargraph#340]
**Describe the bug**
Hi! 
In /data/explorer.py, line 594 (inside the run function from theUniformRandomMetaPathWalk Class) the variable "node" should be "current_node" in order to get the proper neighbors. Currently, the function always gets the neighbors from the source node what eventually leads to break the inner loop as the neighbors are not matching with the expected metapath.

**Comment by youph** [comment]
@PantelisElinas could you please have a look?

**Comment by PantelisElinas** [comment]
Hi @afdezt 

looks like there is a bug there. I'll have a closer look and if so I'll get it fixed in the next few days.

Regards,

P.
