### ISSUE TITLE
Add Python 3.7 support to BuildKite

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#349]
### Description
As Python 3.7 is now the default on many Python distributions, we have added experimental Python 3.7 support to `stellargraph` but currently BuildKite is setup for Python 3.6.

Adding a Python 3.7.2 environment to the BuildKite tests is now required – this can be run in parallel with the current Python 3.6 tests.

This would best be done in the `enable_python37_support` branch connected to PR #348 

### Done Checklist (Development)
- [x] Added Python 3.7.2 environment to BuildKite
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed

**Comment by youph** [comment]
Is this done?

**Comment by adocherty** [comment]
@TheDen I think this is now implemented with the merge of https://github.com/stellargraph/stellargraph/pull/348. Can we close this issue?

**Comment by TheDen** [comment]
Yep, okay with this issue being closed 👍
