### ISSUE TITLE
Add Simple-GCN to the library

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#355]
### Description
The recent [Simple-GCN](https://arxiv.org/abs/1902.07153) algorithm looks quite promising; we should add it to the library and experiment with it.

See [this implementation](https://github.com/danielegrattarola/spektral/blob/master/examples/semi_sup_classification_simple_gc.py) in spektral for reference.

### Done Checklist (Development)\
- [x] Produced code for required functionality
- [x] Unit test coverage
- [x] Demo
- [x] Branch and Pull Request pass unit tests on CI
- [x] Peer Code Review Performed
- [x] Code well commented
- [x] Documentation in repo
- [ ] CHANGELOG.md updated

**Comment by Tiiiger** [comment]
As the first author of this paper, I want to first thank you for creating a great project here and considering including Simple Graph Convolution as an example. I am happy to chat if you have questions and our repo is at https://github.com/Tiiiger/SGC.

One notable feature for SGC is that you can precompute the propagation steps. There are usually two ways to implement this feature:
- Just precompute the propagation and store the resulting features, as in https://github.com/Tiiiger/SGC/blob/master/citation.py#L32
- Use a cached variable to store the resulting features on the model (perhaps more elegant), as in
https://github.com/dmlc/dgl/blob/master/examples/pytorch/sgc/sgc.py#L40

**Comment by PantelisElinas** [comment]
Hi @Tiiiger 

thanks for your suggestions. I'll take them into account when I implement your method within the next couple of weeks and I will definitely be in touch if I need your help.

Regards,

P.
