### ISSUE TITLE
Update API for FullBatchNodeGenerator

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#371]
### Description

@adocherty suggested the following,

"I will note that I don't like passing the function GCN_Aadj_feats_op in the user code and then specifying the arguments in the calling function. I'd prefer having just the arguments specifying the filtering (i.e. filter="smoothing", k=1) and leaving passing a function for advanced usage."

This issue is about updating the API to address the above concern.

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Branch and Pull Request pass integration tests on CI
- [x] Peer Code Review Performed
- [x] Code well commented

**Comment by youph** [comment]
An alternative option is to have a simple `FullBatchNodeGenerator`, and do the normalisation of A inside the model, if necessary (i.e., it is necessary for GCN, and not needed for GAT).
