### ISSUE TITLE
Apply Stellargraph GCN on TfNSW data

### ISSUE THREAD

**Issue by habiba-h** [stellargraph/stellargraph#373]
### Description
**Applying Stellargraph GCN  implementation of the TfNSW data**

### Done Checklist (Development)
- [x] Demo notebook that step-by-step shows how Stellargraph GCN implementation can be applied on the TfNSW data for the purpose of speed forecasting.
- [x] Figure out the appropriate format of the TfNSW data that gets ingested into the GCN such that the results are comparable to the baseline LSTM approach.
- [x] Figure out how to handle the batch dimension of the TfNSW while feeding it into GCN.
- [x] Evaluate the prediction outcomes of GCN with those from LSTM baseline.
- [x] Discuss next steps for extending Stellargraph GCN for application into temporal data.

**Comment by PantelisElinas** [comment]
@habiba-h and @adocherty 

this is continuing work but please split into smaller tickets.
