### ISSUE TITLE
Make all demo notebooks runnable with treon

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#384]
### Description
Treon is an opensource tool from the maker of ReviewNB that allows the automated execution of notebooks as part of a testing framework. Currently to check that our notebooks run, we need to manually run them all. As the number of demos we have is increasing constantly this is becoming infeasible.

Our notebooks are not yet compatible with automated treon runs due to local `utils.py` files not being able to be imported and the availability of datasets.  This task is to:
* Add all dependencies for the demos to `setup.py` to `EXTRAS_REQUIRES`
* Write a script to download the datasets required for all notebooks;
* Fix the imports in the notebooks of local Python functions (i.e. `utils.py`)

This will enable testing of all demo notebooks in a CI in the future.

### Done Checklist (Development)
- [ ] Modify notebooks to work with treon. UPDATE: notebooks don't need to be modified!
- [x] Write script to automate downloading of datasets & running of demo notebooks.
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo
- [ ] Team demo

**Comment by PantelisElinas** [comment]
@habiba-h 

for now, include only the notebooks that we can download the data for. 

P.

**Comment by PantelisElinas** [comment]
Have a chat with @TheDen about the issues with Docker.

P.
