### ISSUE TITLE
package stellargraph for Anaconda

### ISSUE THREAD

**Issue by annitrolla** [stellargraph/stellargraph#406]
### Description
stellargraph can be installed via pip, but it would be nice to `conda`-package it .

### User Story
As a: data scientist
I want: to be able to install stellargraph via conda
so that: it would be easier to download it using Anaconda

### Done Checklist (Development)
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [ ] CHANGELOG.md updated
- [ ] Team demo
- [ ] Mini-meetup talk
- [ ] Stakeholder sign-off

**Comment by adocherty** [comment]
Information on building a `conda` package is available here:

https://conda.io/projects/conda-build/

**Comment by adocherty** [comment]
Duplicated issue: https://github.com/stellargraph/stellargraph/issues/437
