### ISSUE TITLE
Improve documentation for creating graphs to use in StellarGraph

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#409]
### Description

Currently the documentation does not give much information about how to create graphs for use with StellarGraph.  Homogeneneous graphs are straighforward and have many demos showing their use. However, heterogeneous graphs are more difficult and we do not have clear demos that cover all uses.

In particular, we don't demonstrate how to create a graph with multiple edge types occuring between nodes (a `nx.MultiGraph` needs to be created) or that we can use a `nx.Graph` if there are multiple types of nodes but one type of edge.  Additionally, more information on how `stellargraph` obtains the node & edge types would be good.

We should add a section in the documentation describing creating graphs for use with `stellargraph`. This can have the following content:

* Creating homogeneous graphs (supported by GraphSAGE, GCN, GAT, node2vec)
* Creating heterogeneous graphs (supported by HinSAGE, metapath2vec)
  * Graphs with multiple node types
  * Graphs with multiple edge types

### User Story
As a: new user
I want: to create a homogeneous or heterogeneous graph
so that: I can use the graph ML algorithms in stellargraph

### Done Checklist
- [ ] Assumptions of the user story met
- [ ] Documentation in repo
- [ ] CHANGELOG.md updated

**Comment by timpitman** [comment]
This requires a fresh look once #662 is complete.

**Comment by timpitman** [comment]
@huonw I think this may already be addressed by your changes for #723?

**Comment by huonw** [comment]
I think so: https://stellargraph.readthedocs.io/en/latest/api.html#stellargraph.core.StellarGraph

Now starts with a homogeneous graph, and then demonstrates a heterogeneous graph with multiple node types, one with multiple edge types, and one with both.
