### ISSUE TITLE
Tune node2vec parameters for link prediction demo

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#42]
### Description

Currently, the link prediction demo uses fixed parameter values, e.g., p=q=1 and several other parameters, for node2vec. We need to allow for these parameters to be tuned for improved link prediction performance.

### User Story
As a: Research Engineer
I want: to tune the hyper-parameters of the node2vec algorithm  
so that: I can achieve the highest performance in link prediction

### Done Checklist (Development)
- [ ] Code to tune node2vec hyper-parameters
- [ ] Pull request

**Comment by youph** [comment]
@PantelisElinas is this still relevant?

**Comment by youph** [comment]
I agree, so perhaps this should be closed?
