### ISSUE TITLE
AttributeError: 'GraphSAGE' object has no attribute 'node_model'

### ISSUE THREAD

**Issue by mazzma12** [stellargraph/stellargraph#423]
**Describe the bug**
```python
AttributeError: 'GraphSAGE' object has no attribute 'node_model'
```

**To Reproduce**
Run `demos/community_detection/attack_clustering.ipynb`
```python
# Section "Unsupervised graph SAGE"
# Expose input and output sockets of graphsage, for source and destination nodes:
x_inp_src, x_out_src = graphsage.default_model(flatten_output=False)
x_inp_dst, x_out_dst = graphsage.default_model(flatten_output=False)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version : 18.04

- stellargraph: 0.6.1
- 

**Data used**
If this problem appears with a specific dataset you are using, specify how to get the dataset to duplicate the problem.

**Additional context**
Fixed by replacing by `graphsage.default_model()`, but not sure it is the expected replacement.

**Comment by adocherty** [comment]
Hi @mazzma12 

Thanks for reporting the error.  I see that you are using `stellargraph` 0.6.1, and I suspect you are using the demo notebooks from the develop branch on GitHub. The develop branch has a version of GraphSAGE that supports the new `node_model` API for GraphSAGE, but this was not supported in the 0.6.1 release.

To fix this you can either upgrade your `stellargraph` version to the development branch, or use the demo notebooks from the 0.6.1 release:

* To install the develop version of `stellargraph` with these features, run the following pip install command:
```
pip install git+https://github.com/stellargraph/stellargraph.git@develop
```

* To use the 0.6.1 notebooks, download the demos from GitHub by browsing the 0.6.1 release files using the following address: 
https://github.com/stellargraph/stellargraph/tree/v0.6.1

I hope this helps!

Best regards,
Andrew

**Comment by mazzma12** [comment]
Hi @adocherty, you spotted the problem, I installed with PYPI but I  ran the demos in local and I realized the default branch points to `develop` when you clone it. 
This explains the others mismatched I had. 
Fixed.
