### ISSUE TITLE
GraphSAGE and GAT/GCN predictions have different shapes

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#425]
**Describe the bug**

When using a GraphSAGE model the outputs have an extra dimension before the feature dimension that captures the number of head graphs there are (1 for node inference, 2 for link classification).

For example:
```
graphsage_model = GraphSAGE(
    layer_sizes=[32, 32],
    generator=train_gen,
)
>> x_inp, x_out = graphsage_model.build(flatten_output=False)

>> K.int_shape(x_out)
(None, 1, 32)
```

When the `flatten_output=True` argument is specified this extra dimension is flattened:
```
>> x_inp, x_out = graphsage_model.build(flatten_output=True)

>> K.int_shape(x_out)
(None, 32)
```

However, we cannot use this flag with link prediction.

When using a GAT/GCN model the outputs have a single batch dimension and do not have an extra head graph dimension:

For example:
```
gcn = GCN(
    layer_sizes=[16, 16],
    activations=['relu', 'relu'],
    generator=generator,
    )
>> x_inp, x_out = gcn.node_model()

>> K.int_shape(x_out)
(1, None, 16)
```

For single feature outputs we have the following situation:

GraphSAGE must have outputs divisible by 2 so this doesn't work.

For GCN/GAT we have an extra dimension:
```
>> gcn = GCN(
    layer_sizes=[16, 1],
    activations=['relu', 'relu'],
    generator=generator,
    )
>> x_inp, x_out = gcn.node_model()

>> K.int_shape(x_out)
(1, None, 1)
```

This means that the output needs to be flattened before feeding a vector of binary labels to the `.fit` method:
```
>> x_out_flat = layers.Reshape((-1,))(x_out)

>> K.int_shape(x_out)
(1, None)
```

**Expected behavior**
The output shapes from the GraphSAGE and GCN/GAT methods should be closer (apart from the required singleton batch dimension of the full-batch methods). 

Specifically, we should have sensible default behaviour for GraphSAGE and not have to specify the `flatten_output=True` argument:
```
>> x_inp, x_out = graphsage_model.build()

>> K.int_shape(x_out)
(None, 32)
``` 

We can introduce the `flatten_output=True` option to GCN to flatten binary prediction outputs:
```
>> gcn = GCN(
    layer_sizes=[16, 1],
    activations=['relu', 'relu'],
    generator=generator,
    )
>> x_inp, x_out = gcn.node_model(flatten_output=True)

>> K.int_shape(x_out)
(1, None)
```

**Comment by youph** [comment]
@adocherty Actually, for link classification the base model output does not have "2 for link classification", but rather it is a list of length 2, with each element of the list having node output tensor (one for src, one for dst node).

**Comment by youph** [comment]
@adocherty the PR stellargraph/stellargraph#447 seems to fully address this issue now, does it not?
