### ISSUE TITLE
Create Anaconda installer

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#437]
### Description
Anaconda python has it's own repository and installation system. For Anaconda users making stellargraph available in Anaconda Cloud would be advantageous.

Information:
https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/
https://conda.io/projects/conda-build/en/latest/concepts/recipe.html

### User Story
As a: Anaconda Python user
I want: to install stellargraph using native package management
so that: I can use stellargraph easily

### Done Checklist
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] CHANGELOG.md updated
- [ ] README.md updated to include Anaconda install instructions

**Comment by youph** [comment]
- Update release instructions (uploading to conda cloud)
- Conda forge

**Comment by yvonnegh** [comment]
@adocherty @yvonnegh to work together to set up stellar.admin
