### ISSUE TITLE
Add build() method to GCN and GAT classes

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#439]
### Description
This is a continuation of ticket #339, the aim is to add `build()` method to `GCN` and `GAT` classes.

### User Story
As a: user of the library
I want: consistent interface to all model classes
so that: I can easily switch models with minimum code change

### Done Checklist (Development)
- [ ] `build` method added
  - [ ] `GCN.build()`
  - [ ] `GAT.build()`
- [ ] tests updated
- [ ] Demos updated
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] CHANGELOG updated

**Comment by youph** [comment]
Duplicate of #410

**Comment by adocherty** [comment]
Closing this duplicate issue.
