### ISSUE TITLE
Fix source--target node designations for code using Cora dataset

### ISSUE THREAD

**Issue by geoffj-d61** [stellargraph/stellargraph#444]
### Description

The Cora README documentation from the [dataset](https://linqs-data.soe.ucsc.edu/public/lbc/cora.tgz) specifies that the column order is: cited-paper; citing-paper. However, at least one Jupyter notebook (namely [cora-links-example.ipynb](https://github.com/stellargraph/stellargraph/blob/develop/demos/link-prediction/graphsage/cora-links-example.ipynb)) assumes the column ordering: `source`; `target`.

Notwithstanding that this example assumes undirected edges, the constructed graph should accurately reflect the directed relationships inherent in the data.

### How to reproduce (the error): 
The relevant code snippet in the [cora-links-example.ipynb](https://github.com/stellargraph/stellargraph/blob/develop/demos/link-prediction/graphsage/cora-links-example.ipynb) notebook is:
```
edgelist = pd.read_csv(os.path.join(data_dir, "cora.cites"), sep='\t', header=None, names=["source", "target"])
```

### Aim
To locate all code examples that load the Cora dataset, and ensure the loaded graphs utilise the correct target--source citation ordering.

- [x] Bug fixed
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] CHANGELOG.md updated

**Comment by geoffj-d61** [comment]
@adocherty, could you please review this ticket and let me know if I've made any goofs?

**Comment by adocherty** [comment]
Hi @geoffj-d61,

This looks good to me.  I point out that the directionality here is dependent upon the semantics of the link, the current links are a "cited_by" relationship, you are proposing to change this to a "cites" relationship. When we make this change it would be good to add a comment about the semantics of the link.

Note also that a lot of the demo notebooks use CORA with the same code, so we should change all of them.

**Comment by geoffj-d61** [comment]
@adocherty, agreed - I intend to review and fix all occurrences in the demos. Also, I'm not exactly *changing* to a "cites" relationship - this is already explicitly assumed in the notebooks; I am merely correcting the loaded directionality. While I am about it, I am also testing demos in python 3.6/3.7 and trying to understand them.
