### ISSUE TITLE
GraphSAGE/HinSAGE on Directed Graphs

### ISSUE THREAD

**Issue by juliecwang** [stellargraph/stellargraph#460]
I'm interested in applying the HInSAGE algorithm on a multi-edged directed graph and was wondering if the library currently supports directed graphs for the HinSAGE/GraphSAGE models? I believe these algorithms do not naturally support directed graphs, but would it be possible to model directed edges and edge features?

**Comment by adocherty** [comment]
Hi Julie,

Currently StellarGraph does't support directed graphs or edge features. We are currently implementing directed edge support for GraphSAGE and then HinSAGE, so look out for our next release!

Using edge features is not supported in the GraphSAGE/HinSAGE algorithm. We are currently looking for algorithms that allow edge features to be used. If you are aware of any, please let us know!

Regards,
Andrew

**Comment by youph** [comment]
Directed GraphSAGE is available in our recent release (https://github.com/stellargraph/stellargraph/releases/tag/v0.8.2).

**Comment by youph** [comment]
@youph Separate this issue into 2: GraphSAGE and HinSAGE

**Comment by timpitman** [comment]
I'm closing this 'epic' now, with HinSAGE work to continue in #563.  @juliecwang could you please try the directed GraphSAGE, and let us know any new requirements for HinSAGE in #563?

Thanks,
Tim
