### ISSUE TITLE
Inconsistency in Ensemble.fit_generator() argument

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#461]
### Description
The `Ensemble.fit_generator()` method's argument `validation_generator` is inconsistent with Keras `Model.fit_generator()`'s argument `validation_data`. This means that one can't simply add a line `model = Ensemble(model, n_estimators=n_estimators, n_predictions=n_predictions)` to a workflow to use model ensembles instead of a single model, one also needs to modify the call to `model.fit_generator()` method.
The desired behaviour is to have `Ensemble.fit_generator(validation_data=...)`, so that one can use the same `model.fit_generator()` call, regardless of whether `model` is a single Keras model or an Ensemble object.

### Done Checklist (Bug)
- [x] Bug fixed
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Peer Code Review Performed
- [x] Code well commented
- [x] CHANGELOG.md updated

**Comment by youph** [comment]
@PantelisElinas I believe this has been fixed recently?

**Comment by PantelisElinas** [comment]
Hi @youph this issue was solved as part of issue #413. 

This one can be closed now.

Regards,

P.
