### ISSUE TITLE
Can weighted graphs be used inGraphSAGE?

### ISSUE THREAD

**Issue by ericbroda** [stellargraph/stellargraph#462]
I have graphs that have weights that reflect the relative importance of some relationships compared to others.  In other words, some links between nodes have lower weights (low importance) and others have higher weights (high importance).

This could be very useful for clustering and perhaps even node classification in situations where weights are available.

Is there a way to have GraphSAGE take this into account?

**Comment by adocherty** [comment]
Hi Eric,

Currently edge weights are not supported in GraphSAGE. We are looking into possible ways to take edge weights into account. We will update this issue when we do.

Best regards,
Andrew

**Comment by colinwxl** [comment]
I am also interested in GraphSAGE on the weighted graph. In my opinion, it should consider both the `sampling` procedure and the `link-prediction` part.

**Comment by mimisen-boop** [comment]
> This could be very useful for clustering and perhaps even node classification in situations where weights are available.

Could you specify more about ideas that might be useful with node classification?

**Comment by huonw** [comment]
We've now merged #1667, which adds support for edge weights in GraphSAGE sampling. Edge weights can be used for training a link prediction model too.

**Comment by patchy631** [comment]
> We've now merged #1667, which adds support for edge weights in GraphSAGE sampling. Edge weights can be used for training a link prediction model too.

How can i use the edge weights as one of the parameters for link prediction?
Right now I'm trying to make some changes to sampled_link_generator.py, so that with every batch i also append the corresponding edge weight as a parameter. Plz help if a better way exists.

**Comment by adocherty** [comment]
Hi,

I'm not clear as to what you are interested in doing with the edge weights.  Could you tell us more about how you envisage the edge weight to be used as a parameter for link prediction?

**Comment by patchy631** [comment]
Hi @adocherty
I'm working with a road network graph. Each node in my stellar graph is a single digital road element, it's neighbouring nodes would be the roads directly connected to it in reality. So on the edge i have number of vehicles going from a road to it's neighbour connected via this edge. So for doing link prediction I need to inculcate this traffic data present on the edge as one of the parameter for downstream classification.

So link data is like:  (node1_data)-----edge_data-----(node2_data)

Thanks
