### ISSUE TITLE
Create options for adding regularization to weights for GCN/GraphSAGE/HinSAGE

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#469]
### Description

The GCN class has an optional `kernel_regularizer` argument that allows adding regularization to the weights of the layers. The GAT, GraphSAGE, and HinSAGE classes do not support this option, even though the GraphAttention layer has these options. 

This issue is to add options for adding regularization to the weights for these classes that do not have it. Some design decisions should be made for how granular to allow regularization: for example should this be different for the different types of weights (for example, the attention weights vs the layer weights in GAT).

This is important to Anna who would like to use this for use-case investigations.

This also supercedes this issue: #172 

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by geoffj-d61** [comment]
Hi @annitrolla , could I please get your input on this issue? I'm interested in getting an overview of how you would use these weights, e.g. what interpretation would the weights have for you for a particular problem, and how would they affect the answers?

**Comment by annitrolla** [comment]
I think it should be very similar for other models (graphSAGE, HinSAGE) to what we have currently in gcn:
```
gcn = GCN(
    layer_sizes=[16, 16],
    activations=['relu', 'relu'],
    generator=generator,
    kernel_regularizer = regularizers.l2(0.01),
    dropout=0.5
)
```
This will allow us to penalise the weights (https://keras.io/regularizers/) which might improve the models. I don't think we need to interpret those weights, but adding them might improve the results. I hope it will answer your questions. If not, let's discuss it further.

**Comment by geoffj-d61** [comment]
In regards to the question of granularity, for GraphSAGE and HinSAGE the base aggregator layer has a secret `_initializer` variable that is applied to all weights. Hence, following GCN, GraphSAGE and HinSAGE now optionally accept weight (kernel) and bias initialisers, regularisers and constraints, and these are passed to the aggregators and applied to ALL weights and biases, respectively.

**Comment by geoffj-d61** [comment]
Thanks @annitrolla , that's good - it gives me a definite use-case I can add to the tests. I've added and tested string versions of the initialisers, now I can also test the regularisers, via both string and function.

**Comment by geoffj-d61** [comment]
Notes:
- Added various regularisers (etc.) to GraphSAGE.
- Added various regularisers to HinSAGE.
- Ensured GAT took optional regularisers and actually passed them to attention layers.
- Ensured GCN took **all** optional regularisers and passed them to convolution layers. 
- Fixed and added tests for all four classes with regards to regularisation.
