### ISSUE TITLE
Replace Keras with tf.keras

### ISSUE THREAD

**Issue by cdawei** [stellargraph/stellargraph#471]
Tensorflow has an implementation of the Keras API [since v1.4.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0) and `tf.keras` will be [one of the mainly promoted interfaces](https://www.tensorflow.org/beta/guide/effective_tf2#use_keras_layers_and_models_to_manage_variables) in Tensorflow 2.0, which is supposed to be supported by stellargraph in the near future.

If we replace `keras.xxx` with `tensorflow.keras.xxx`, Keras could be safely dropped from the list of requirements. As a side bonus, there's no more waiting for Keras to officially support Python 3.7 :)

This can be seen as a preliminary work on #379, and I am happy to create pull requests if people think it is a worthwhile effort.

**Comment by youph** [comment]
@cdawei this would be valuable, you're welcome to create a PR :)
