### ISSUE TITLE
Design for CD2L-GM graph matching algorithm

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#473]
### Description

We want to understand how we can implement the CD2L-GM algorithm in StellarGraph.

Read the paper, and do some high level design to understand if we can implement it using existing components or if we need to implement new components.

### Done Checklist (Development)
- [ ] Documentation on Google Docs
- [ ] Team demo

**Comment by EmmaXue** [comment]
CD2L-GM algorithm would be implemented from the published work Cross-domain Network Representation (http://gnosis.stellargraph.xyz/catalog/paper/899/). This work achieves graph matching in two seperate steps. One step is node matching across two independent graphs (each node in target graph to a group of nodes called super node in source graph). Within this step, potential links across graphs are predicted. The following step is path matching between paths (formed by generated super edges connecting super nodes) in source graph and edges in target graph. Jointly contributed by node matching and path matching, the graph matching output a set of updated edges on target graph as well as their weights, from which we can do further node embedding or whatever. The aim of this algorithm is to enrich structures of target graph by learning from source graph in predicting potential links across two graphs.

The CD2L-GM algorithm could be implemented into two classes corresponding to the node matching and path matching respectively.
