### ISSUE TITLE
Unsupervised GraphSage speed up 

### ISSUE THREAD

**Issue by mattivi** [stellargraph/stellargraph#474]
**Describe the bug**
Time to train Unsupervised GraphSage is too high, infeasible for large graphs. Training time is same for CPU or GPU.

**To Reproduce**
1. Go to notebook  unsupervised graph sage core (https://github.com/stellargraph/stellargraph/blob/master/demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb)
2. Run it with the standard parameters in that notebook demo example (which means "Running GraphSAGELinkGenerator with an estimated 542 batches generated on the fly per epoch". and running for 4 epochs.
** With CPU it takes 109s per epoch
** With GPU it takes 106s per epoch
The previous stats are for a small graph (G.info()): 
StellarGraph: Undirected multigraph
Nodes: 2708, Edges: 5278

**Desktop**
 - Windows 10
 - Anaconda environment. 
 - Latest master stellargraph version (pip install stellargraph[demo])
 - GPU Nvidia GTX 1080

**Questions**
I am aware there is currently use_multiprocessing=False and workers=0, as specified in the notebook. Will the fix be provided soon?
Is there a way to speed up the training process? GPU and CPU provides same training time.

For much larger graphs, e.g.  600k+ nodes and 3M+ edges the computation time will become excessively high (GraphSAGELinkGenerator will easily go up to 30k+ batches per epoch).

Thanks for the support!

**Comment by youph** [comment]
@habiba-h @PantelisElinas FYI
@geoffj-d61 will we be able to address this in the next sprint?

**Comment by youph** [comment]
@mattivi thanks for raising this issue. We'll try to address this in our next sprint.

**Comment by youph** [comment]
Note that setting `use_multiprocessing=False` and more than one worker (e.g., `workers=4`) does speed up the training, but occasionally throws an error `ValueError: generator already executing`, which is probably related to some multithreading issue.

**Comment by youph** [comment]
Actually I just applied a fix in https://github.com/stellargraph/stellargraph/pull/477, @PantelisElinas @geoffj-d61 please review.

**Comment by youph** [comment]
@mattivi we've applied the fix, see PR https://github.com/stellargraph/stellargraph/pull/477 and the performance tests in the discussion there. Hope this helps!

**Comment by mattivi** [comment]
It works as expected, thanks a lot!
