### ISSUE TITLE
Implement Cluster GCN

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#487]
### Description

Cluster-GCN, [1], is a scalable and inductive extension of the GCN algorithm.

This ticket is about implementing Cluster-GCN in StellarGraph for node attribute inference with demo Jupyter notebook.

[1], Cluster-GCN: An Efficient Algorithm for Training Deep and Large Graph Convolutional Networks, W. Chiang, X. Liu, S. Si, Y. Li, S. Bengio, C. Hsieh, KDD, 2019.

### User Story
As a: research engineer
I want: to add new scalable algorithms to the StellarGraph library
so that: I can use them to build good predictive models of my data.

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Version number reflects new status
- [ ] Peer Code Review Performed
- [x] Code well commented
- [x] Documentation in repo
- [x] CHANGELOG.md updated
- [x] Team demo

**Comment by huonw** [comment]
(For ease of reference, e.g. if this turns up in a search, this was implemented in https://github.com/stellargraph/stellargraph/pull/521.)
