### ISSUE TITLE
model.fit no longer works for GAT (and probably GCN)

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#491]
### Description
After the additional "batch" dimension was introduced, the `model.fit` method no longer works for GAT and GCN models. @adocherty FYI

To reproduce:
- get the latest `develop` version
- cd to `demos/node-classification/gat`
- run `python gat-cora-example.py -l ~/data/cora -i fit`

The error:
```
Traceback (most recent call last):
  File "gat-cora-example.py", line 359, in <module>
    args.dropout,
  File "gat-cora-example.py", line 168, in train
    callbacks=[es_callback, tb_callback, mc_callback],
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 652, in fit
    batch_size, steps_per_epoch, x)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1902, in _validate_or_infer_batch_size
    per_replica_batch_size, static_batch_size))
ValueError: The `batch_size` argument value 2708 is incompatible with the specified batch size of your Input Layer: 1
```

## Desired behaviour
Both `fit` and `fit_generator` methods should work for full-batch models.

### Done Checklist (Bug)
- [ ] Bug fixed
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] CHANGELOG.md updated

**Comment by Orbifold** [comment]
The example only works right now by installing TensorFlow v1.12 (on Python3.6) or TensorFlow v1.13 (on Python3.7).
In addition, change

`from tensorflow.keras import layers, optimizers, losses, metrics, Model`
 
to

`from keras import layers, optimizers, losses, metrics, Model`.
