### ISSUE TITLE
Investigate Turi for graph processing in the ML library and platform

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#52]
### Description
Apple has open-sourced Turi which is a powerful graph processing framework. We should evaluate this tech with the following critera:
- functionality
- easy of use
- easy of scalability
- performance

This task would be to ingest a > 1M edge dataset and perform a set of graph tasks e.g. BFS/DFS, graph traversal, grabbing neighbours, random sampling.

### User Story
As a: data scientist 
I want: the graph processing part of the library to be fast and have lots of functionality
so that: I can move on to my tensorflow part to build my model

### Done Checklist (Development)
- [ ] Small experiment setup to run the evaluation, e.g. python script file
- [ ] Documentation on Google Docs
- [ ] Team demo

**Comment by adocherty** [comment]
This is being done by d2d.
