### ISSUE TITLE
Failed to run graphsage demo

### ISSUE THREAD

**Issue by hlltc** [stellargraph/stellargraph#527]
Failed to run demo/node-classification/graphsage/graphsage-cora-excample.py  and graphsage-cora-node-classification-example.ipynb

```python
Traceback (most recent call last):
  File "graphsage-cora-example.py", line 356, in <module>
    args.dropout,
  File "graphsage-cora-example.py", line 124, in train
    aggregator=MeanAggregator,
  File "D:\Program Files\Python\Python36\lib\site-packages\stellargraph\layer\graphsage.py", line 772, in __init__
    self._get_sizes_from_generator(generator)
  File "D:\Program Files\Python\Python36\lib\site-packages\stellargraph\layer\graphsage.py", line 811, in _get_sizes_from_generator
    self.n_samples = generator.generator.num_samples
AttributeError: 'GraphSAGENodeGenerator' object has no attribute 'generator'
```

Is there anything wrong with GraphSageNodeGenerator?

**Comment by hlltc** [comment]
python                 3.5.8
stellargraph         0.8.2

**Comment by adocherty** [comment]
Hi,

Thanks for trying out the StellarGraph library.  It looks like you are running demos from the develop branch but the library is version 0.8.2.  We have made some API changes on the develop branch that are incompatible with the latest released version.

Could you try downloading the demos from v0.8.2 on GitHub, using the following address:
https://github.com/stellargraph/stellargraph/tree/v0.8.2

If this doesn't work for you, please let us know.

Regards,
Andrew

**Comment by hlltc** [comment]
Thanks. 
It works!
