### ISSUE TITLE
[Demo] demos\node-classification\graphsage>python graphsage-cora-example.py giving error

### ISSUE THREAD

**Issue by jjindia** [stellargraph/stellargraph#532]
node-classification\graphsage\graphsage-cora-example.py is not executing. Please find the below Trace message

**Describe the bug**

Traceback (most recent call last):
  File "graphsage-cora-example.py", line 356, in <module>
    args.dropout,
  File "graphsage-cora-example.py", line 124, in train
    aggregator=MeanAggregator,
  File "C:\Users\JJ\Anaconda3\envs\oldenv\lib\site-packages\stellargraph\layer\graphsage.py", line 772, in __init__
    self._get_sizes_from_generator(generator)
  File "C:\Users\JJ\Anaconda3\envs\oldenv\lib\site-packages\stellargraph\layer\graphsage.py", line 811, in _get_sizes_from_generator
    self.n_samples = generator.generator.num_samples
AttributeError: 'GraphSAGENodeGenerator' object has no attribute 'generator'
**To Reproduce**
2. Execute '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu]
 - Version [e.g. 18.01]

**Data used**
If this problem appears with a specific dataset you are using, specify how to get the dataset to duplicate the problem.

**Additional context**

**Comment by youph** [comment]
@jjindia what version of the library are you using? (obtainable by running `pip show stellargraph` in the terminal of your virtual environment)

**Comment by dubbsbrandon** [comment]
I was having a similar issue and I reinstalled within the directory today, but I am still having  the same issue. Is there a temporary workaround or is there a patch or update coming out that the demo will reflect the code that should be used? Or is there another notebook that I could reference in the meantime?

**Comment by youph** [comment]
@dubbsbrandon what version of stellargraph shows after you re-installed within the directory? And how exactly did you re-install, I.e., what command you used?

**Comment by kevin-meng** [comment]
> I was having a similar issue and I reinstalled within the directory today, but I am still having the same issue. Is there a temporary workaround or is there a patch or update coming out that the demo will reflect the code that should be used? Or is there another notebook that I could reference in the meantime?

i have the same problem when I use the ' pip install  stellargraph' . and the version is 0.8.2 

but when i clone the source code and use 'python setup.py install '  can perfect run the demo code
without errors. and the version is 0.9.0b0.

you can try it

**Comment by dubbsbrandon** [comment]
I did that last night. Seems to work perfectly now once I completely reinstalled it. Thanks for the help. This can probably be closed now.
