### ISSUE TITLE
Check demo scripts and notebooks on CI

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#575]
### Description

Currently, our notebooks are not validated on CI, which can lead to problems like #570 / #571, where they aren't updated after a change.

### User Story

**As** a data scientist

**I want to** be able to pick up any working demo

**So that** I learn to use stellargraph

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by timpitman** [comment]
We could avoid the block on #610 by starting with just cora and the notebooks test script at  https://github.com/stellargraph/stellargraph/blob/develop/scripts/test_demos.py
