### ISSUE TITLE
Establish an experimental/beta algorithm process

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#617]
### Description

In order to keep velocity high and friction low, we have the idea of landing algorithms and features as experimental or "beta", and then iterating for a little (e.g. improving the API, optimising speed and adding documentation/demos) before they graduate to be generally available.

If we're going to do this, we need an easy process to manage it and sure things don't get too stuck.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
(This is a proposal comment, everything here is just my opinion and fully open for discussion.)

I think there's two parts of this:

- how to indicate an API is experimental /beta (technical)
- how to decide to promote an API to non-experimental/beta (social)

### Indicating experimental/beta status

I have three ideas for this:

1. a submodule like `stellargraph.experimental` or `stellargraph.beta` that contains various experimental algorithms similar to `tensorflow.experimental` ([1](https://www.tensorflow.org/api_docs/python/tf/experimental), [2](https://stackoverflow.com/questions/58333491/what-does-experimental-in-tensorflow-mean)), and could potentially be more fine-grained, e.g. `stellargraph.layer.experimental`, `stellargraph.mapper.experimental` (TF also has `tensorflow.keras.experimental`). An experimental improvement would initially land in that submodule/subfolder, and then is moved to the appropriate non-experimental module
2. having an attribute like `@experimental` or `@beta` that modifies the class or function (e.g. adding `This is experimental, and may change at any moment` to the docs)
3. have some sort of actual check, so that users get an exception if they try to use (or import?) an experimental feature without setting a flag of some sort, for instance, we might have a `stellargraph.allow_experimental()`/`stellargraph.allow_beta()` and/or check an environment variable like `STELLARGRAPH_ALLOW_BETA`, and require them to be called (or set) before importing an `experimental`/beta` module (for 1) or using an `@experimental`/`@beta` class/function (for 2), otherwise they through an exception 

These can be combined.

### Promotion

The process for promotion could probably be lightweight for now, e.g., a checklist like:

- [ ] Has some tests
- [ ] Has documentation for all classes, functions and their parameters
- [ ] Has a demo

We could potentially add other criteria, for instance:

- [ ] Ran profiler(s)
- [ ] Has test coverage about some threshold

But I suspect having too much process will mean we end up with a library full of experimental functionality, and nothing new that's non-experimental.

**Comment by kjun9** [comment]
> ### Indicating experimental/beta status

IMO just starting with idea 1 seems fine. The rest could be nice to have if we actually notice idea 1 by itself not being clear enough?

> ### Promotion

A short checklist sounds good 👍

**Comment by timpitman** [comment]
Happy with the decorator approach (Option 2) that's landed (potentially with an expansion to providing a warning at runtime in addition to the documentation change).  I agree that the promotion checklist should be lightweight to prevent a lot of algorithms getting stuck in experimental status 👍
