### ISSUE TITLE
Neighbour based methods in Stellargraph class

### ISSUE THREAD

**Issue by habiba-h** [stellargraph/stellargraph#635]
### Description
Adding methods in the `StellarGraph` class to access neighbours for a node or a list (subset of nodes of a graph) with or without a specified `edge_type`.

 The `StellarGraph` class has the following three methods defined. 

`def neighbors(self, node: Any) -> Iterable[Any]`
`def in_nodes(self, node: Any) -> Iterable[Any]`
`def out_nodes(self, node: Any) -> Iterable[Any]`

We need to extends these to be in the form `def neighbors(self, node: Any, data: Optional[List[str]] = None, edge_types: Optional[List[str]] = None)` or something along those lines. This is needed to do things like edge-type or edge-attribute aware random walks efficiently.

### User Story
As a: research engineer 
I want: to access neighbors/in_nodes/out_nodes for a specific node
so that: 
I can implement random walks.

### Done Checklist (Development)
- [x] Assumptions of the user story met
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [x] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [x] CHANGELOG.md updated
- [ ] Team demo
- [ ] Mini-meetup talk
- [ ] Stakeholder sign-off

**Comment by kjun9** [comment]
Okay since we don't actually support a full set of edge features, only a single feature as a "weight", I'm now thinking we would have something like:

```python
    def neighbors(self, node: Any, weight=False, edge_types=None) -> Iterable[Any]:
        """
        Obtains the collection of neighbouring nodes connected
        to the given node.

        Args:
            node (any): The node in question.
            weight (bool, default False): If True, each neighbour in the output is a
                tuple of (node ID, edge weight)
            edge_types (list of str, optional): If provided, only traverse the graph
                via the provided edge types when collecting neighbours.

        Returns:
            iterable: The neighbouring nodes.
        """
```

**Comment by habiba-h** [comment]
This would still be able to support multiple edges though? In temporal graphs, even if we ignore different types of edge features, except time, there are going to  be multiple edges with distinct times for a pair of nodes.

**Comment by habiba-h** [comment]
Also, the time feature can be  a user defined label? Networkx by default label the edge feature as weight but this can be changed and depending on the dataset it could be named differently.

**Comment by kjun9** [comment]
> This would still be able to support multiple edges though? In temporal graphs, even if we ignore different types of edge features, except time, there are going to be multiple edges with distinct times for a pair of nodes.

Yes I think this should be fine. Calling `graph.neighbors(node)` you may end up getting multiple items in return that point to the same neighbouring node, but with different times associated with them.

> Also, the time feature can be a user defined label? Networkx by default label the edge feature as weight but this can be changed and depending on the dataset it could be named differently.

Yes, it looks like you should be able to create the StellarGraph class like:
```python
nxg = nx.MultiDiGraph()
...
g = StellarGraph(g=nxg, edge_weight_label="time")
```
Then it should use the "time" attribute from the networkx graph `nxg` when you call other `StellarGraph` methods later that try to access weights.
