### ISSUE TITLE
Handling different node types

### ISSUE THREAD

**Issue by ocesp98** [stellargraph/stellargraph#700]
As I am using different node types in my graph (some node types have features, others not) I encountered a problem while implementing GraphSAGE. I know that the current model requires node features for all nodes in the graph, but this is not the case. Is there any way around this?

**Comment by huonw** [comment]
Hi @ocesp98. GraphSAGE is designed for homogeneous graphs, where all nodes and edges are the same type. It sounds like you have a heterogeneous graph, where there's more than one type of node and/or more than one type of edge. StellarGraph offers some algorithms for heterogeneous graphs. One example is HinSAGE: https://github.com/stellargraph/stellargraph/tree/develop/demos/node-classification/hinsage

**Comment by PantelisElinas** [comment]
Hi @ocesp98 

On the other issue of some of your nodes not having features, I don't think that there is a very good way around it. Usually, if none of the nodes in your graph have attributes/features, then one can still use GraphSAGE/HinSAGE by using an identity matrix as the input features; if your graph has N nodes, then this would be an NxN identity matrix. Unfortunately, if only some of your nodes are missing attributes, then the latter is unlikely to work. Not sure what to do in this case!

Regards,

P.

**Comment by kjun9** [comment]
Usually if some nodes have features and others do not, it's a difficult problem to work around as @PantelisElinas says, but

> some node types have features, others not

if this is **consistently** the case (e.g. all nodes of type `A` has features, and all nodes of type `B` does not, etc), then I think you *could* try assigning the NxN identity matrix **per node type** for those node types that don't have features, and then proceed with an algorithm that supports heterogeneous graphs such as HinSAGE. 

Here's an example for the case when you have two node types and one of them doesn't have features:

```python
import networkx as nx
import numpy as np
import stellargraph as sg

nxg = ...  # load your networkx graph containing nodes of type A and B
A_features = ...  # load your features for node type A

# creating "features" for B
B_ids = ...  # list of node IDs for all nodes of type B
B_features = pd.DataFrame(np.identity(len(B_ids)), index= B_ids)

g = sg.StellarGraph(nxg, features={
    "A": A_features
    "B": B_features
})
```
and for the rest of the pipeline, the example @huonw mentions should be good to follow!

**Comment by huonw** [comment]
Hi @ocesp98, have we addressed your problem here?
