### ISSUE TITLE
Finish implementation of Spotify Challenge for HinSAGE

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#71]
### Description
The team has written code for the Spotify challenge, we have a partially complete Graphsage model. To finish off this implementation we need to:

* Load fasttext features for Playlist nodes
* Implement sampling schemes for positive & negative links
* Output predictions in required format for evaluation

### Done Checklist
- [ ] Code Review
- [ ] Documentation in repo
- [ ] Test on subset of Spotify data

**Comment by adocherty** [comment]
This could be addressed in the next Hackathon:
https://docs.google.com/document/d/1k4NU9uUDTz7BkG--0udcbFlB7j7gjF49E9EFNtNqHrI/edit

**Comment by huonw** [comment]
@adocherty Is still relevant? If not, can we close this?

**Comment by adocherty** [comment]
I do not think this is relevant anymore 😞
