### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'head_node_type'

### ISSUE THREAD

**Issue by ocesp98** [stellargraph/stellargraph#712]
When I was implementing HinSAGE as it is done in the demos, I encountered the following error:
`    generator = HinSAGENodeGenerator(G, batch_size, num_samples, head_node_type="peer")`
TypeError: __init__() got an unexpected keyword argument 'head_node_type'
However, in the documentation, head_node_type is one of the arguments that can be used. The 'peer' node type is the only node type I should be able to predict so supplying all the node types makes no sense. 

What should I do about this?
Thank you in advance for the help on this matter!

**Comment by huonw** [comment]
Hi @ocesp98, as before, thanks for using the library. However, we would very much appreciate if you could use our bug template. For example, it will confirm what version of `stellargraph` library you're using. This will help us help you. 😄 

In this case, a link to the documentation page you're looking at would be great too.

I suspect you're looking at the `latest` documentation, which is the documentation for the `develop` branch (i.e. under active development): https://stellargraph.readthedocs.io/en/latest/api.html#stellargraph.mapper.HinSAGENodeGenerator

If you're using stellargraph 0.8.3 or 0.8.4 (or other released version), you should be looking at either:

- https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.mapper.HinSAGENodeGenerator (note the `/stable/`)
- https://stellargraph.readthedocs.io/en/v0.8.4/api.html#stellargraph.mapper.HinSAGENodeGenerator (note the `/v0.8.4/`)

On read-the-docs, project versions can be changed using the drop down in the bottom left:

![image](https://user-images.githubusercontent.com/1203825/72939753-9cfc8a00-3dc1-11ea-9bc1-334b297373ef.png)

Similarly, the best demos to look at for a released version will be either:

- https://github.com/stellargraph/stellargraph/tree/master/demos (note the `/master/` meaning the latest release)
- https://github.com/stellargraph/stellargraph/tree/v0.8.4/demos (note the `/v0.8.4/`)

(I apologise for linking to the `develop` ones in https://github.com/stellargraph/stellargraph/issues/700, that was my mistake.)

---

> However, in the documentation, head_node_type is one of the arguments that can be used. The 'peer' node type is the only node type I should be able to predict so supplying all the node types makes no sense.

I believe this is also controlled by only specifying nodes of the `peer` type as the `node_ids` to `.flow`: if only nodes with `peer` type are specified, then it will only train and predict on those.

**Comment by huonw** [comment]
Hi @ocesp98, did the above resolve your problem? Do you need some other help?

**Comment by ocesp98** [comment]
Yes, this problem is solved. Thank you very much for your help!
