### ISSUE TITLE
'from .foo import *' reexports are invisible in documentation

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#713]
### Describe the bug

We've got a lot of `__init__` files that reexport some or all of their submodule contents, e.g.:

https://github.com/stellargraph/stellargraph/blob/10e62006907dd5968286f33648d1054e9c961c1b/stellargraph/__init__.py#L32-L46

https://github.com/stellargraph/stellargraph/blob/10e62006907dd5968286f33648d1054e9c961c1b/stellargraph/utils/__init__.py#L22-L24

However this doesn't seem to be visible in the documentation, e.g.:

- `StellarGraph` is only listed as `stellargraph.core.StellarGraph` https://stellargraph.readthedocs.io/en/latest/api.html#stellargraph.core.StellarGraph, but is available as `stellargraph.StellarGraph`
- `Ensemble` is only listed as `stellargraph.utils.ensemble.Ensemble` https://stellargraph.readthedocs.io/en/latest/api.html#stellargraph.utils.ensemble.Ensemble, but is available as both `stellargraph.Ensemble` and `stellargraph.utils.Ensemble`

(develop at the time of writing: 10e62006907dd5968286f33648d1054e9c961c1b).

### To Reproduce

1. Go to the API documentation https://stellargraph.readthedocs.io/en/latest/api.html
2. Compare the import paths against `__init__` files

### Observed behavior

There's only a single listing of each of the types, without any mention of reexports.

### Expected behavior

Some sort of indication of more convenient import paths, e.g. only listing them.

### Environment

N/A

### Additional context

N/A

**Comment by kjun9** [comment]
Tensorflow's docs seems to have a dropdown to view aliases - e.g. https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy#view-aliases

Maybe we can do something like that?
