### ISSUE TITLE
Top-level __all__ doesn't match attempted reexports

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#714]
### Describe the bug

Our top level `__init__` file imports and reexports types like `Ensemble` and `TemperatureCalibration`, but these are not listed in `__all__`. This is somewhat unconventional (as I understand it), and, if it's on purpose, should probably be explicitly noted:

https://github.com/stellargraph/stellargraph/blob/10e62006907dd5968286f33648d1054e9c961c1b/stellargraph/__init__.py#L22-L30

https://github.com/stellargraph/stellargraph/blob/10e62006907dd5968286f33648d1054e9c961c1b/stellargraph/__init__.py#L40-L49

### To Reproduce

1. View `stellargraph/__init__.py`

### Observed behavior

`__all__` does not list many of the names in the rest of `__init__.py`

### Expected behavior

`__all__` should match the names in the rest of the file, or there should be some explanation otherwise.

### Environment

N/A

### Additional context

N/A

**Comment by PantelisElinas** [comment]
Hi @huonw 

I don't recall why it is as it is. We should probably update as necessary.

P.
