### ISSUE TITLE
Update link prediction demo script to use new datasets module to access Cora and BlogCatalog3

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#758]
### Description

Identified in #610, the script `demos/link-prediction/random-walks/main.py` relies on manual download of Coa and BlogCatalog3 datasets (and manual conversion and pickling of BlogCatalog3). The script can be updated to automatically download and convert/cache these datasets.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by timpitman** [comment]
This has been replaced by #889 which removed the script, leaving just the Jupyter notebook.

**Comment by kjun9** [comment]
This might be relevant again: https://github.com/stellargraph/stellargraph/issues/895

**Comment by timpitman** [comment]
Closing, as this script will be replaced with #934 which will be a random walk link prediction demo with heterogeneous graph (BlogCatalog3).
