### ISSUE TITLE
Implement GraphSAGE using DL4J and Spark

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#77]
### Description
Chao is currently working on combining DL4J and Spark, we need to make sure that GraphSAGE works in this setup. This task is to build a Scala GraphSAGE application example that uses the platform team's tools.

This can be written in the stellar-platform repo as and example.

- Finish unit tests for input preparation code
- GraphX to RDDs function
- Integrate with rest of Stellar platform library
- Test full pipeline on EMR

### Done Checklist
- [x] Branch and Pull Request build on CI
- [x] Peer Code Review Performed
- [x] Code well commented
- [x] Unit Tests

**Comment by xiaozhi-alan-zhu** [comment]
Hello team, I was wondering if there is any example of using StellarGraph on EMR? Thanks!
