### ISSUE TITLE
Some algorithms supported in StellarGraph via demos aren't listed in documentation on readthedocs

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#805]
### Describe the bug

In StellarGraph, some algorithms are in demo notebooks or scripts, without being listed in our main documentation.  This could mean that a user reading our docs thinks they're not supported in StellarGraph.

**Comment by huonw** [comment]
Do you have a (partial) list of which algorithms?

**Comment by huonw** [comment]
We've updated various bits of documentation to include more algorithms, like the demos table: https://stellargraph.readthedocs.io/en/stable/demos/index.html#find-a-demo-for-an-algorithm

As such, I'm calling this done.
