### ISSUE TITLE
Watch Your Step algorithm

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#813]
### Description

This is an Epic to cover the work of adding the "watch your step" NEGA algorithm from "Learning Node Embeddings via Graph Attention" https://arxiv.org/abs/1710.09599

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
Is this epic done now?
