### ISSUE TITLE
Write unit tests for GraphWave

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#815]
### Description

The current GraphWave is experimental because it doesn't have unit tests. This issue is to write unit tests for GraphWave covering:

- [ ] `stellargraph.mapper.graphwave_generator.GraphWaveGenerator`
- [ ] `stellargraph.mapper.graphwave_generator._empirical_characteristic_function`

### Done Checklist

- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated

**Comment by huonw** [comment]
Was this done in #920?

**Comment by kieranricardo** [comment]
yeah, this was done in #920 I'll move this issue over
