### ISSUE TITLE
Chebyshev filter in FullbatchNodeGenerator is not covered in any demos

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#825]
### Describe the bug

#411 found issues with the Chebyshev filter - these would have been picked up earlier if the filter was actually used in any of our demos!

Rather than creating yet another cut-and-pasted cora convolution demo, could it be included with another (possibly with a results (accuracy/speed etc) comparison at the end?)

If we really don't want it in a notebook, then it should at least have sufficient tests to be sure that it works.

**Comment by kjun9** [comment]
This option is being removed in #1028
