### ISSUE TITLE
Investigate reducing notebook CI stages to t2medium buildkite agents once new SG class is rolled out

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#840]
### Description

Currently the notebook CI (for #575) is using t2large instances, since a handful of notebooks take too much ram for t2medium.  Potential efficiencies with the new StellarGrpah class may allow us to switch to using t2medium, with associated cost savings.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
This is now irrelevant with the switch to Github Actions in #1687.
