### ISSUE TITLE
format_notebooks.py could normalise "stream" output to non-stream

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#842]
### Description

Jupyters models interactively updated output as `"output_type": "stream"`, which is great for progress bars in interactive output, but not so great when saving that to a file: the incremental updates are all saved, but only the final result is interesting.

For example,  https://github.com/stellargraph/stellargraph/blob/baff22bcee03382c83d7e9e9f104c5a5d46552d9/demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb?short_path=2c8374e#L401-L440 was run and saved with `format_notebooks.py --execute` and has 10k+ lines of progress bar updates.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by timpitman** [comment]
see #826 for another different issue with cell output
