### ISSUE TITLE
`NetworkXStellarGraph` with `node_features=None` has empty `node_index_maps`

### ISSUE THREAD

**Issue by kieranricardo** [stellargraph/stellargraph#852]
### Describe the bug

Calling `._get_index_for_nodes()` from a `NetworkXStellarGraph` with `node_features=None` returns a `KeyError` because `.node_index_maps` are empty. Graph initialised without features can still be used with many unsupervised embedding algorithms for which `._get_index_for_nodes()` is often a useful function.

### To Reproduce

```
import networkx as nx
from stellargraph import StellarGraph

gnx = nx.barbell_graph(m1=10, m2=10)
G = StellarGraph(gnx)

nodes = list(G.nodes())
G._get_index_for_nodes(nodes)
```

### Observed behaviour

This returns a `KeyError`.

### Expected behaviour

Returns indices for the nodes provided for graphs with no features.

### Environment

Operating system: macOS

Python version: 3.6.9

Package versions: stellargraph==0.10.0b, networkx==2.4

**Comment by huonw** [comment]
https://github.com/stellargraph/stellargraph/pull/809 is merged which deletes `NetworkXStellarGraph`, and thus this no longer applies.
