### ISSUE TITLE
how to train on own dataset for node classification.

### ISSUE THREAD

**Issue by vigneshgig** [stellargraph/stellargraph#854]
i have csv file having node ,edges and multi- label value. how can i train using rgcn node classification.
@huonw 
Thanks

**Comment by huonw** [comment]
Hi, we'd love to help you, but you'll need to give us a little more information. Have you tried some code yet? If so, could you post it and an explain why it isn't matching what you expect?

If you haven't tried some code yet, could you explain what's stopping you, and then we can help you resolve it?

**Comment by huonw** [comment]
Hi @vigneshgig, we're excited to help you if you're having troubles, but we definitely need some more information. Could you post a small section of the data and the code you're using to load it?

**Comment by huonw** [comment]
It's been 2 months without any update, so I'm going to assume that the problem is resolved. If we haven't heard otherwise in a week or so, we'll close. (But, even if we close, feel free to just let us know later, and we can reopen/continue the discussion.)
