### ISSUE TITLE
Error handling could be improved when node IDs appear in edges but not in nodes (new StellarGraph)

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#894]
### Description

Many datasets only contain an edgelist and the user needs to manually create a nodelist to go along with it in order to create a `StellarGraph` class, so it would be good to catch cases where this hasn't been done correctly with a clear error message. 

Currently, this doesn't result in a failure not upon construction, but later when trying to access node IDs via their ilocs from calling methods like `graph.info`, and it appears that when a node ID doesn't exist, somewhere it gets assigned an iloc that is the max value of the dtype

Minimal example:

```python
from stellargraph import StellarGraph
import pandas as pd

nodes = pd.DataFrame([], index=[1])
edges = pd.DataFrame({"source": [1], "target": [2]})
g = StellarGraph(nodes=nodes, edges=edges)
g.info()
```

output:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-3a08a89e54d8> in <module>
      5 edges = pd.DataFrame({"source": [1], "target": [2]})
      6 g = StellarGraph(nodes=nodes, edges=edges)
----> 7 g.info()

~/work/stellar/stellargraph/stellargraph/core/graph.py in info(self, show_attributes, sample)
    750 
    751         # Numpy processing is much faster than NetworkX processing, so we don't bother sampling.
--> 752         gs = self.create_graph_schema()
    753 
    754         def str_edge_type(et):

~/work/stellar/stellargraph/stellargraph/core/graph.py in create_graph_schema(self, nodes)
    807 
    808         for n1, rel, n2 in self._unique_type_triples(
--> 809             selector=selector, return_counts=False
    810         ):
    811             edge_type_tri = EdgeType(n1, rel, n2)

~/work/stellar/stellargraph/stellargraph/core/graph.py in _unique_type_triples(self, return_counts, selector)
    701 
    702     def _unique_type_triples(self, *, return_counts, selector=slice(None)):
--> 703         all_type_ilocs = self._edge_type_iloc_triples(selector, stacked=True)
    704 
    705         if len(all_type_ilocs) == 0:

~/work/stellar/stellargraph/stellargraph/core/graph.py in _edge_type_iloc_triples(self, selector, stacked)
    681 
    682         target_ilocs = self._nodes.ids.to_iloc(self._edges.targets[selector])
--> 683         target_type_ilocs = self._nodes.type_ilocs[target_ilocs]
    684 
    685         all_ilocs = source_type_ilocs, rel_type_ilocs, target_type_ilocs

IndexError: index 255 is out of bounds for axis 0 with size 1
```

### User Story

**As** a ...

**I want to** [accomplish some things]

**So that** [achieve a larger goal]

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
> Many datasets only contain an edgelist and the user needs to manually create a nodelist to go along with it in order to create a StellarGraph class, so it would be good to catch cases where this hasn't been done correctly with a clear error message.

In addition to improving the error handling, we could allow `StellarGraph(edges=...)` only, and infer the node list.

**Comment by huonw** [comment]
Work-arounds when only the edges are explicitly specified:

Single edge type (i.e. `edges` is a dataframe like in the issue):

```python
sources_and_targets = pd.concat([edges.source, edges.target]))
nodes = pd.DataFrame(index=pd.unique(sources_and_targets))

g = StellarGraph(nodes, edges)
```

Multiple edge types (`edges` is a dict of data frames):

```python
# example data:
edges = {
    "a": pd.DataFrame({"source": [1], "target": [2]}), 
    "b": pd.DataFrame({"source": [2], "target": [3]}, index=[1])
}

sources_and_targets = pd.concat(
    [series for df in edges.values() for series in [df.source, df.target]]
)
nodes = pd.DataFrame(index=pd.unique(sources_and_targets))

g = StellarGraph(nodes, edges)
```

Both of these assume there's only one node type.
