### ISSUE TITLE
Removed demo script for link prediction via random walks had different scenarios not covered by the notebook

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#895]
### Description

#889 removed a lot of demo scripts that were duplicating what was being demonstrated in notebooks already, but [this script](https://github.com/stellargraph/stellargraph/blob/0f64ef0597c433a3abe8ed1e3ee62ff2940aa1a0/demos/link-prediction/random-walks/main.py) for link prediction actually contained a few different options to use a heterogeneous graph using metapath2vec that is not covered by the notebook. The notebook only covers using node2vec on cora (homogeneous), so currently a lot of the functions for dealing with heterogeneous graphs and metapath2vec in the `utils` module of the demo is unused.

Ideally we should create a new notebook that covers the missed options, but alternatively we could just bring back the old demo script for now.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by timpitman** [comment]
I'm going to restore the script for now; later we can look at #934.
