### ISSUE TITLE
Examples section in readthedocs is outdated

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#900]
### Describe the bug

Examples section at https://stellargraph.readthedocs.io/en/latest/quickstart.html#getting-started refers to scripts that no longer exist, when it should refer to demo notebooks.  It also discusses downloading the CORA dataset, which is no longer required.

Ideally, we should have a table linking to our demos which clearly indicates the type of problem, and the algorithm used.

**Comment by kjun9** [comment]
@timpitman I'm wondering if this whole page should just be identical to our top-level README - it seems like the contents are pretty much the same (introduction, getting started, installation, examples). I think it's less likely to get outdated that way, and it seems like we should just be able to point to the markdown file https://stackoverflow.com/questions/46278683/include-my-markdown-readme-into-sphinx

**Comment by kjun9** [comment]
> it seems like we should just be able to point to the markdown file

Hmm seems it doesn't work well enough actually, the table of contents aren't handled nicely and internal links get broken. I'll try some alternatives

**Comment by kjun9** [comment]
Managed to get something working using `recommonmark` and `sphinx-markdown-tables` #1096
