### ISSUE TITLE
GraphWave blog post

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#903]
### Description

Create a blog post for GraphWave (potential promotional material for the 1.0 release) - likely showing a worked example and some background.

### Done Checklist

- [x] KR + LK finalise draft ready for review
- [x] TP review/provide feedback
- [x] KR create Medium profile
- [x] KR load draft to Medium and submit to StellarGraph
- [x] LK prepare cover image
- [x] LK prepare blog for publishing 
- [ ] Final sign-off from AC 
- [ ] LK publish

**Comment by LedaKalleske** [comment]
Blog now ready for peer review from @timpitman. Propose to publish to Medium Wed, 29 April.

**Comment by yvonnegh** [comment]
Scheduled for after 5 May release

**Comment by yvonnegh** [comment]
Challenges with preparing a reasonable use case for GraphSage, perhaps just focus on the algorithm..
