### ISSUE TITLE
move Neo4J sampling code from demo notebooks to StellarGraph library

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#904]
### Description

Investigate developing the Neo4J demo further, bringing Neo4J sampling into the SteallrGraph library.

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
The sampling code already is in the library, and the notebooks use it, e.g. cell 11 in https://github.com/stellargraph/stellargraph/blob/8684379f7016645e451f32eec4cea4c430392151/demos/connector/neo4j/undirected-graphsage-on-cora-neo4j-example.ipynb

```python
generator = Neo4JGraphSAGENodeGenerator(G, batch_size, num_samples, neo4j_graphdb)
```

It's at https://github.com/stellargraph/stellargraph/blob/8684379f7016645e451f32eec4cea4c430392151/stellargraph/connector/neo4j/sampler.py

Thus, moving this to done.
