### ISSUE TITLE
MUTAG dataset

### ISSUE THREAD

**Issue by PantelisElinas** [stellargraph/stellargraph#927]
### Description

This ticket is about adding the MUTAG dataset to stellargraph.datasets. MUTAG is a commonly used dataset for evaluating graph classification algorithms. 

Each graph in the dataset represents a chemical compound and graph labels represent "their mutagenic effect on a specific gram negative bacterium". The dataset includes 188 graphs with 18 nodes and 20 edges on average for each graph. Graph nodes have 7 labels and each graph is labelled as belonging to 1 of 2 classes.

Download link: https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/
FIle: MUTAG.zip

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] CHANGELOG.md updated

**Comment by alexbui91** [comment]
In Mutag, it has two classes. Which one means Mutagenic?
