### ISSUE TITLE
ValueError: must have at least one node for inference, if `node_type` is not specified

### ISSUE THREAD

**Issue by sbhttchryy** [stellargraph/stellargraph#972]
On trying to reproduce the RGCN example on AIFB dataset, I am running into the above error.
I am running the notebook on Google Colab and had tried with both installing the stellargraph package as well as the stellargraph[demo] package. Both of them show this error on the line:

generator = RelationalFullBatchNodeGenerator(G, sparse=True)

The entire trace is as follows:
ValueError                                Traceback (most recent call last)
<ipython-input-29-704246492183> in <module>()
----> 1 generator = RelationalFullBatchNodeGenerator(G, sparse=True)
      2 
      3 train_gen = generator.flow(train_data.index, targets=train_targets)
      4 test_gen = generator.flow(test_data.index, targets=test_targets)

1 frames
/usr/local/lib/python3.6/dist-packages/stellargraph/core/graph.py in node_features(self, nodes, node_type)
    737             if len(types) == 0:
    738                 raise ValueError(
--> 739                     "must have at least one node for inference, if `node_type` is not specified"
    740                 )
    741             if len(types) > 1:

ValueError: must have at least one node for inference, if `node_type` is not specified

**Comment by timpitman** [comment]
Hi @sbhttchryy, thank you for reporting the issue with this notebook.  I believe this is the same as #911 which we'll be fixing soon - we'll update you once it's resolved.

**Comment by huonw** [comment]
Thanks again for filing an issue; #983 has landed, so it should now be fixed on `develop`.
