### ISSUE TITLE
Add "get started" basic tutorial notebook(s) to teach users how to create a StellarGraph and do basic ML workflow.

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#992]
### Description

Split from #910 - Our current set of demo notebooks are good to show particular algorithms, but don't teach the basics of how to create a StellarGraph from a dataset on disk, then use it for a basic ML workflow.

We can create two (or possibly one?) tutorial notebooks that show:
1. how to load/preprocess data to build a StellarGraph
    * can be based on existing notebooks, but with a focus on documenting the c ore workflow, rather than specific algorithm or results.
    * need to cover homogeneous and heterogeneous data sets. (possibly CORA for homog; could include our own CSV for hetero. ) 

~~2. the very basics of the machine learning workflow (something very simple like GCN node classification)
    * important now that are examples are using the `datasets` module to return a `StelalrGraph` object rather than explicit code in the notebook.~~

### User Story

**As a new user to StellarGraph, I want a basic tutorial showing me how to load data and construct a StellarGraph, ~~then construct the basic machine learning workflow~~ so that I can understand the library and use it on my own datasets**

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
I've split https://github.com/stellargraph/stellargraph/issues/1087 off to cover how we surface these (and other) notebooks, leaving this one to just create the notebooks.
